#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 80
#define LARGE_STATE_COUNT 15
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 6
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_CR = 2,
  anon_sym_CR_LF = 3,
  anon_sym_NULL = 4,
  sym_word = 5,
  sym_ws = 6,
  aux_sym_punc_token1 = 7,
  aux_sym_punc_token2 = 8,
  aux_sym_punc_token3 = 9,
  anon_sym_STAR = 10,
  anon_sym_SLASH = 11,
  anon_sym_BQUOTE = 12,
  anon_sym_DOT = 13,
  anon_sym_COLON = 14,
  sym__paragraph_break = 15,
  sym__open_conflict = 16,
  sym__close_conflict = 17,
  sym_bold_close = 18,
  sym_italic_close = 19,
  sym_verbatim_close = 20,
  sym_document = 21,
  sym_paragraph = 22,
  sym_punc = 23,
  sym_link_modifier = 24,
  sym_verbatim_open = 25,
  sym_verbatim = 26,
  sym__verbatim_non_ws = 27,
  sym_bold_open = 28,
  sym__bold_non_ws = 29,
  sym_bold = 30,
  sym_italic_open = 31,
  sym__italic_non_ws = 32,
  sym_italic = 33,
  sym__non_ws = 34,
  aux_sym_document_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_CR] = "\r",
  [anon_sym_CR_LF] = "\r\n",
  [anon_sym_NULL] = "\0",
  [sym_word] = "word",
  [sym_ws] = "ws",
  [aux_sym_punc_token1] = "punc_token1",
  [aux_sym_punc_token2] = "punc_token2",
  [aux_sym_punc_token3] = "punc_token3",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_DOT] = ".",
  [anon_sym_COLON] = ":",
  [sym__paragraph_break] = "_paragraph_break",
  [sym__open_conflict] = "punc",
  [sym__close_conflict] = "_close_conflict",
  [sym_bold_close] = "bold_close",
  [sym_italic_close] = "italic_close",
  [sym_verbatim_close] = "verbatim_close",
  [sym_document] = "document",
  [sym_paragraph] = "paragraph",
  [sym_punc] = "punc",
  [sym_link_modifier] = "link_modifier",
  [sym_verbatim_open] = "verbatim_open",
  [sym_verbatim] = "verbatim",
  [sym__verbatim_non_ws] = "_verbatim_non_ws",
  [sym_bold_open] = "bold_open",
  [sym__bold_non_ws] = "_bold_non_ws",
  [sym_bold] = "bold",
  [sym_italic_open] = "italic_open",
  [sym__italic_non_ws] = "_italic_non_ws",
  [sym_italic] = "italic",
  [sym__non_ws] = "_non_ws",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_CR] = anon_sym_CR,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [anon_sym_NULL] = anon_sym_NULL,
  [sym_word] = sym_word,
  [sym_ws] = sym_ws,
  [aux_sym_punc_token1] = aux_sym_punc_token1,
  [aux_sym_punc_token2] = aux_sym_punc_token2,
  [aux_sym_punc_token3] = aux_sym_punc_token3,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym__paragraph_break] = sym__paragraph_break,
  [sym__open_conflict] = sym_punc,
  [sym__close_conflict] = sym__close_conflict,
  [sym_bold_close] = sym_bold_close,
  [sym_italic_close] = sym_italic_close,
  [sym_verbatim_close] = sym_verbatim_close,
  [sym_document] = sym_document,
  [sym_paragraph] = sym_paragraph,
  [sym_punc] = sym_punc,
  [sym_link_modifier] = sym_link_modifier,
  [sym_verbatim_open] = sym_verbatim_open,
  [sym_verbatim] = sym_verbatim,
  [sym__verbatim_non_ws] = sym__verbatim_non_ws,
  [sym_bold_open] = sym_bold_open,
  [sym__bold_non_ws] = sym__bold_non_ws,
  [sym_bold] = sym_bold,
  [sym_italic_open] = sym_italic_open,
  [sym__italic_non_ws] = sym__italic_non_ws,
  [sym_italic] = sym_italic,
  [sym__non_ws] = sym__non_ws,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NULL] = {
    .visible = true,
    .named = false,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_ws] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_punc_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_punc_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_punc_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym__paragraph_break] = {
    .visible = false,
    .named = true,
  },
  [sym__open_conflict] = {
    .visible = true,
    .named = true,
  },
  [sym__close_conflict] = {
    .visible = false,
    .named = true,
  },
  [sym_bold_close] = {
    .visible = true,
    .named = true,
  },
  [sym_italic_close] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_close] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_punc] = {
    .visible = true,
    .named = true,
  },
  [sym_link_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_open] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim] = {
    .visible = true,
    .named = true,
  },
  [sym__verbatim_non_ws] = {
    .visible = false,
    .named = true,
  },
  [sym_bold_open] = {
    .visible = true,
    .named = true,
  },
  [sym__bold_non_ws] = {
    .visible = false,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic_open] = {
    .visible = true,
    .named = true,
  },
  [sym__italic_non_ws] = {
    .visible = false,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym__non_ws] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 7,
  [14] = 8,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 18,
  [21] = 19,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 31,
  [35] = 32,
  [36] = 36,
  [37] = 36,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 32,
  [44] = 42,
  [45] = 36,
  [46] = 41,
  [47] = 38,
  [48] = 33,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 38,
  [56] = 56,
  [57] = 57,
  [58] = 57,
  [59] = 57,
  [60] = 60,
  [61] = 61,
  [62] = 61,
  [63] = 32,
  [64] = 61,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (!eof && lookahead == 0) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead == ' ') ADVANCE(11);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == ':') ADVANCE(22);
      if (lookahead == '`') ADVANCE(20);
      if (lookahead == 'w') ADVANCE(3);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '`') ADVANCE(19);
      if (lookahead == 'w') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'd') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(2);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_CR);
      if (lookahead == '\n') ADVANCE(8);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_CR_LF);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_NULL);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_word);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_ws);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_punc_token1);
      if (lookahead == '*') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_punc_token2);
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_punc_token3);
      if (lookahead == '`') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(12);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == '`') ADVANCE(14);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 4},
  [8] = {.lex_state = 0, .external_lex_state = 5},
  [9] = {.lex_state = 0, .external_lex_state = 4},
  [10] = {.lex_state = 0, .external_lex_state = 5},
  [11] = {.lex_state = 0, .external_lex_state = 4},
  [12] = {.lex_state = 0, .external_lex_state = 5},
  [13] = {.lex_state = 0, .external_lex_state = 4},
  [14] = {.lex_state = 0, .external_lex_state = 5},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 6},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 4},
  [23] = {.lex_state = 0, .external_lex_state = 5},
  [24] = {.lex_state = 0, .external_lex_state = 5},
  [25] = {.lex_state = 0, .external_lex_state = 5},
  [26] = {.lex_state = 0, .external_lex_state = 4},
  [27] = {.lex_state = 0, .external_lex_state = 4},
  [28] = {.lex_state = 0, .external_lex_state = 3},
  [29] = {.lex_state = 0, .external_lex_state = 3},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0, .external_lex_state = 5},
  [32] = {.lex_state = 0, .external_lex_state = 5},
  [33] = {.lex_state = 0, .external_lex_state = 3},
  [34] = {.lex_state = 0, .external_lex_state = 3},
  [35] = {.lex_state = 0, .external_lex_state = 4},
  [36] = {.lex_state = 0, .external_lex_state = 3},
  [37] = {.lex_state = 0, .external_lex_state = 4},
  [38] = {.lex_state = 0, .external_lex_state = 4},
  [39] = {.lex_state = 0, .external_lex_state = 3},
  [40] = {.lex_state = 0, .external_lex_state = 2},
  [41] = {.lex_state = 0, .external_lex_state = 5},
  [42] = {.lex_state = 0, .external_lex_state = 3},
  [43] = {.lex_state = 0, .external_lex_state = 3},
  [44] = {.lex_state = 0, .external_lex_state = 4},
  [45] = {.lex_state = 0, .external_lex_state = 5},
  [46] = {.lex_state = 0, .external_lex_state = 3},
  [47] = {.lex_state = 0, .external_lex_state = 5},
  [48] = {.lex_state = 0, .external_lex_state = 4},
  [49] = {.lex_state = 0, .external_lex_state = 4},
  [50] = {.lex_state = 0, .external_lex_state = 3},
  [51] = {.lex_state = 0, .external_lex_state = 5},
  [52] = {.lex_state = 0, .external_lex_state = 5},
  [53] = {.lex_state = 0, .external_lex_state = 3},
  [54] = {.lex_state = 0, .external_lex_state = 4},
  [55] = {.lex_state = 0, .external_lex_state = 3},
  [56] = {.lex_state = 0, .external_lex_state = 7},
  [57] = {.lex_state = 0, .external_lex_state = 7},
  [58] = {.lex_state = 0, .external_lex_state = 7},
  [59] = {.lex_state = 0, .external_lex_state = 7},
  [60] = {.lex_state = 0, .external_lex_state = 7},
  [61] = {.lex_state = 0, .external_lex_state = 2},
  [62] = {.lex_state = 0, .external_lex_state = 2},
  [63] = {.lex_state = 0, .external_lex_state = 7},
  [64] = {.lex_state = 0, .external_lex_state = 2},
  [65] = {.lex_state = 0, .external_lex_state = 2},
  [66] = {.lex_state = 0, .external_lex_state = 2},
  [67] = {.lex_state = 0, .external_lex_state = 2},
  [68] = {.lex_state = 0, .external_lex_state = 2},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_CR] = ACTIONS(1),
    [anon_sym_CR_LF] = ACTIONS(1),
    [anon_sym_NULL] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_ws] = ACTIONS(1),
    [aux_sym_punc_token1] = ACTIONS(1),
    [aux_sym_punc_token2] = ACTIONS(1),
    [aux_sym_punc_token3] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym__paragraph_break] = ACTIONS(1),
    [sym__open_conflict] = ACTIONS(1),
    [sym__close_conflict] = ACTIONS(1),
    [sym_bold_close] = ACTIONS(1),
    [sym_italic_close] = ACTIONS(1),
    [sym_verbatim_close] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(78),
    [sym_paragraph] = STATE(2),
    [sym_punc] = STATE(6),
    [sym_verbatim_open] = STATE(64),
    [sym_verbatim] = STATE(29),
    [sym_bold_open] = STATE(18),
    [sym_bold] = STATE(29),
    [sym_italic_open] = STATE(21),
    [sym_italic] = STATE(29),
    [sym__non_ws] = STATE(6),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_CR] = ACTIONS(7),
    [anon_sym_CR_LF] = ACTIONS(5),
    [anon_sym_NULL] = ACTIONS(5),
    [sym_word] = ACTIONS(9),
    [aux_sym_punc_token1] = ACTIONS(11),
    [aux_sym_punc_token2] = ACTIONS(11),
    [aux_sym_punc_token3] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(11),
    [sym__close_conflict] = ACTIONS(11),
  },
  [2] = {
    [sym_paragraph] = STATE(3),
    [sym_punc] = STATE(6),
    [sym_verbatim_open] = STATE(64),
    [sym_verbatim] = STATE(29),
    [sym_bold_open] = STATE(18),
    [sym_bold] = STATE(29),
    [sym_italic_open] = STATE(21),
    [sym_italic] = STATE(29),
    [sym__non_ws] = STATE(6),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_LF] = ACTIONS(21),
    [anon_sym_CR] = ACTIONS(23),
    [anon_sym_CR_LF] = ACTIONS(21),
    [anon_sym_NULL] = ACTIONS(21),
    [sym_word] = ACTIONS(9),
    [aux_sym_punc_token1] = ACTIONS(11),
    [aux_sym_punc_token2] = ACTIONS(11),
    [aux_sym_punc_token3] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(11),
    [sym__close_conflict] = ACTIONS(11),
  },
  [3] = {
    [sym_paragraph] = STATE(3),
    [sym_punc] = STATE(6),
    [sym_verbatim_open] = STATE(64),
    [sym_verbatim] = STATE(29),
    [sym_bold_open] = STATE(18),
    [sym_bold] = STATE(29),
    [sym_italic_open] = STATE(21),
    [sym_italic] = STATE(29),
    [sym__non_ws] = STATE(6),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_LF] = ACTIONS(27),
    [anon_sym_CR] = ACTIONS(30),
    [anon_sym_CR_LF] = ACTIONS(27),
    [anon_sym_NULL] = ACTIONS(27),
    [sym_word] = ACTIONS(33),
    [aux_sym_punc_token1] = ACTIONS(36),
    [aux_sym_punc_token2] = ACTIONS(36),
    [aux_sym_punc_token3] = ACTIONS(36),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(42),
    [anon_sym_BQUOTE] = ACTIONS(45),
    [anon_sym_DOT] = ACTIONS(36),
    [anon_sym_COLON] = ACTIONS(36),
    [sym__close_conflict] = ACTIONS(36),
  },
  [4] = {
    [sym_punc] = STATE(5),
    [sym_verbatim_open] = STATE(64),
    [sym_verbatim] = STATE(29),
    [sym_bold_open] = STATE(18),
    [sym_bold] = STATE(29),
    [sym_italic_open] = STATE(21),
    [sym_italic] = STATE(29),
    [sym__non_ws] = STATE(5),
    [anon_sym_LF] = ACTIONS(48),
    [anon_sym_CR] = ACTIONS(50),
    [anon_sym_CR_LF] = ACTIONS(48),
    [sym_word] = ACTIONS(48),
    [sym_ws] = ACTIONS(48),
    [aux_sym_punc_token1] = ACTIONS(48),
    [aux_sym_punc_token2] = ACTIONS(48),
    [aux_sym_punc_token3] = ACTIONS(48),
    [anon_sym_STAR] = ACTIONS(50),
    [anon_sym_SLASH] = ACTIONS(50),
    [anon_sym_BQUOTE] = ACTIONS(50),
    [anon_sym_DOT] = ACTIONS(48),
    [anon_sym_COLON] = ACTIONS(48),
    [sym__paragraph_break] = ACTIONS(48),
    [sym__close_conflict] = ACTIONS(48),
  },
  [5] = {
    [sym_punc] = STATE(5),
    [sym_verbatim_open] = STATE(64),
    [sym_verbatim] = STATE(29),
    [sym_bold_open] = STATE(18),
    [sym_bold] = STATE(29),
    [sym_italic_open] = STATE(21),
    [sym_italic] = STATE(29),
    [sym__non_ws] = STATE(5),
    [anon_sym_LF] = ACTIONS(52),
    [anon_sym_CR] = ACTIONS(54),
    [anon_sym_CR_LF] = ACTIONS(52),
    [sym_word] = ACTIONS(52),
    [sym_ws] = ACTIONS(52),
    [aux_sym_punc_token1] = ACTIONS(52),
    [aux_sym_punc_token2] = ACTIONS(52),
    [aux_sym_punc_token3] = ACTIONS(52),
    [anon_sym_STAR] = ACTIONS(54),
    [anon_sym_SLASH] = ACTIONS(54),
    [anon_sym_BQUOTE] = ACTIONS(54),
    [anon_sym_DOT] = ACTIONS(52),
    [anon_sym_COLON] = ACTIONS(52),
    [sym__paragraph_break] = ACTIONS(52),
    [sym__close_conflict] = ACTIONS(52),
  },
  [6] = {
    [sym_punc] = STATE(5),
    [sym_verbatim_open] = STATE(64),
    [sym_verbatim] = STATE(29),
    [sym_bold_open] = STATE(18),
    [sym_bold] = STATE(29),
    [sym_italic_open] = STATE(21),
    [sym_italic] = STATE(29),
    [sym__non_ws] = STATE(5),
    [anon_sym_LF] = ACTIONS(56),
    [anon_sym_CR] = ACTIONS(58),
    [anon_sym_CR_LF] = ACTIONS(56),
    [sym_word] = ACTIONS(9),
    [sym_ws] = ACTIONS(56),
    [aux_sym_punc_token1] = ACTIONS(11),
    [aux_sym_punc_token2] = ACTIONS(11),
    [aux_sym_punc_token3] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(11),
    [sym__paragraph_break] = ACTIONS(60),
    [sym__close_conflict] = ACTIONS(11),
  },
  [7] = {
    [sym_punc] = STATE(11),
    [sym_verbatim_open] = STATE(61),
    [sym_verbatim] = STATE(27),
    [sym_bold_open] = STATE(20),
    [sym_bold] = STATE(27),
    [sym__italic_non_ws] = STATE(11),
    [anon_sym_LF] = ACTIONS(62),
    [anon_sym_CR] = ACTIONS(64),
    [anon_sym_CR_LF] = ACTIONS(62),
    [sym_word] = ACTIONS(66),
    [sym_ws] = ACTIONS(62),
    [aux_sym_punc_token1] = ACTIONS(68),
    [aux_sym_punc_token2] = ACTIONS(68),
    [aux_sym_punc_token3] = ACTIONS(68),
    [anon_sym_STAR] = ACTIONS(70),
    [anon_sym_SLASH] = ACTIONS(72),
    [anon_sym_BQUOTE] = ACTIONS(74),
    [anon_sym_DOT] = ACTIONS(68),
    [anon_sym_COLON] = ACTIONS(68),
    [sym__close_conflict] = ACTIONS(68),
    [sym_italic_close] = ACTIONS(76),
  },
  [8] = {
    [sym_punc] = STATE(12),
    [sym_verbatim_open] = STATE(62),
    [sym_verbatim] = STATE(25),
    [sym__bold_non_ws] = STATE(12),
    [sym_italic_open] = STATE(19),
    [sym_italic] = STATE(25),
    [anon_sym_LF] = ACTIONS(78),
    [anon_sym_CR] = ACTIONS(80),
    [anon_sym_CR_LF] = ACTIONS(78),
    [sym_word] = ACTIONS(82),
    [sym_ws] = ACTIONS(78),
    [aux_sym_punc_token1] = ACTIONS(84),
    [aux_sym_punc_token2] = ACTIONS(84),
    [aux_sym_punc_token3] = ACTIONS(84),
    [anon_sym_STAR] = ACTIONS(86),
    [anon_sym_SLASH] = ACTIONS(88),
    [anon_sym_BQUOTE] = ACTIONS(90),
    [anon_sym_DOT] = ACTIONS(84),
    [anon_sym_COLON] = ACTIONS(84),
    [sym__close_conflict] = ACTIONS(84),
    [sym_bold_close] = ACTIONS(92),
  },
  [9] = {
    [sym_punc] = STATE(11),
    [sym_verbatim_open] = STATE(61),
    [sym_verbatim] = STATE(27),
    [sym_bold_open] = STATE(20),
    [sym_bold] = STATE(27),
    [sym__italic_non_ws] = STATE(11),
    [anon_sym_LF] = ACTIONS(94),
    [anon_sym_CR] = ACTIONS(96),
    [anon_sym_CR_LF] = ACTIONS(94),
    [sym_word] = ACTIONS(94),
    [sym_ws] = ACTIONS(94),
    [aux_sym_punc_token1] = ACTIONS(94),
    [aux_sym_punc_token2] = ACTIONS(94),
    [aux_sym_punc_token3] = ACTIONS(94),
    [anon_sym_STAR] = ACTIONS(96),
    [anon_sym_SLASH] = ACTIONS(96),
    [anon_sym_BQUOTE] = ACTIONS(96),
    [anon_sym_DOT] = ACTIONS(94),
    [anon_sym_COLON] = ACTIONS(94),
    [sym__close_conflict] = ACTIONS(94),
    [sym_italic_close] = ACTIONS(94),
  },
  [10] = {
    [sym_punc] = STATE(12),
    [sym_verbatim_open] = STATE(62),
    [sym_verbatim] = STATE(25),
    [sym__bold_non_ws] = STATE(12),
    [sym_italic_open] = STATE(19),
    [sym_italic] = STATE(25),
    [anon_sym_LF] = ACTIONS(98),
    [anon_sym_CR] = ACTIONS(100),
    [anon_sym_CR_LF] = ACTIONS(98),
    [sym_word] = ACTIONS(98),
    [sym_ws] = ACTIONS(98),
    [aux_sym_punc_token1] = ACTIONS(98),
    [aux_sym_punc_token2] = ACTIONS(98),
    [aux_sym_punc_token3] = ACTIONS(98),
    [anon_sym_STAR] = ACTIONS(100),
    [anon_sym_SLASH] = ACTIONS(100),
    [anon_sym_BQUOTE] = ACTIONS(100),
    [anon_sym_DOT] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [sym__close_conflict] = ACTIONS(98),
    [sym_bold_close] = ACTIONS(98),
  },
  [11] = {
    [sym_punc] = STATE(11),
    [sym_verbatim_open] = STATE(61),
    [sym_verbatim] = STATE(27),
    [sym_bold_open] = STATE(20),
    [sym_bold] = STATE(27),
    [sym__italic_non_ws] = STATE(11),
    [anon_sym_LF] = ACTIONS(102),
    [anon_sym_CR] = ACTIONS(104),
    [anon_sym_CR_LF] = ACTIONS(102),
    [sym_word] = ACTIONS(102),
    [sym_ws] = ACTIONS(102),
    [aux_sym_punc_token1] = ACTIONS(102),
    [aux_sym_punc_token2] = ACTIONS(102),
    [aux_sym_punc_token3] = ACTIONS(102),
    [anon_sym_STAR] = ACTIONS(104),
    [anon_sym_SLASH] = ACTIONS(104),
    [anon_sym_BQUOTE] = ACTIONS(104),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_COLON] = ACTIONS(102),
    [sym__close_conflict] = ACTIONS(102),
    [sym_italic_close] = ACTIONS(102),
  },
  [12] = {
    [sym_punc] = STATE(12),
    [sym_verbatim_open] = STATE(62),
    [sym_verbatim] = STATE(25),
    [sym__bold_non_ws] = STATE(12),
    [sym_italic_open] = STATE(19),
    [sym_italic] = STATE(25),
    [anon_sym_LF] = ACTIONS(106),
    [anon_sym_CR] = ACTIONS(108),
    [anon_sym_CR_LF] = ACTIONS(106),
    [sym_word] = ACTIONS(106),
    [sym_ws] = ACTIONS(106),
    [aux_sym_punc_token1] = ACTIONS(106),
    [aux_sym_punc_token2] = ACTIONS(106),
    [aux_sym_punc_token3] = ACTIONS(106),
    [anon_sym_STAR] = ACTIONS(108),
    [anon_sym_SLASH] = ACTIONS(108),
    [anon_sym_BQUOTE] = ACTIONS(108),
    [anon_sym_DOT] = ACTIONS(106),
    [anon_sym_COLON] = ACTIONS(106),
    [sym__close_conflict] = ACTIONS(106),
    [sym_bold_close] = ACTIONS(106),
  },
  [13] = {
    [sym_punc] = STATE(11),
    [sym_verbatim_open] = STATE(61),
    [sym_verbatim] = STATE(27),
    [sym_bold_open] = STATE(20),
    [sym_bold] = STATE(27),
    [sym__italic_non_ws] = STATE(11),
    [anon_sym_LF] = ACTIONS(62),
    [anon_sym_CR] = ACTIONS(64),
    [anon_sym_CR_LF] = ACTIONS(62),
    [sym_word] = ACTIONS(66),
    [sym_ws] = ACTIONS(62),
    [aux_sym_punc_token1] = ACTIONS(68),
    [aux_sym_punc_token2] = ACTIONS(68),
    [aux_sym_punc_token3] = ACTIONS(68),
    [anon_sym_STAR] = ACTIONS(70),
    [anon_sym_SLASH] = ACTIONS(72),
    [anon_sym_BQUOTE] = ACTIONS(74),
    [anon_sym_DOT] = ACTIONS(68),
    [anon_sym_COLON] = ACTIONS(68),
    [sym__close_conflict] = ACTIONS(68),
    [sym_italic_close] = ACTIONS(110),
  },
  [14] = {
    [sym_punc] = STATE(12),
    [sym_verbatim_open] = STATE(62),
    [sym_verbatim] = STATE(25),
    [sym__bold_non_ws] = STATE(12),
    [sym_italic_open] = STATE(19),
    [sym_italic] = STATE(25),
    [anon_sym_LF] = ACTIONS(78),
    [anon_sym_CR] = ACTIONS(80),
    [anon_sym_CR_LF] = ACTIONS(78),
    [sym_word] = ACTIONS(82),
    [sym_ws] = ACTIONS(78),
    [aux_sym_punc_token1] = ACTIONS(84),
    [aux_sym_punc_token2] = ACTIONS(84),
    [aux_sym_punc_token3] = ACTIONS(84),
    [anon_sym_STAR] = ACTIONS(86),
    [anon_sym_SLASH] = ACTIONS(88),
    [anon_sym_BQUOTE] = ACTIONS(90),
    [anon_sym_DOT] = ACTIONS(84),
    [anon_sym_COLON] = ACTIONS(84),
    [sym__close_conflict] = ACTIONS(84),
    [sym_bold_close] = ACTIONS(112),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(9), 1,
      sym_word,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      anon_sym_SLASH,
    ACTIONS(17), 1,
      anon_sym_BQUOTE,
    STATE(18), 1,
      sym_bold_open,
    STATE(21), 1,
      sym_italic_open,
    STATE(64), 1,
      sym_verbatim_open,
    STATE(4), 2,
      sym_punc,
      sym__non_ws,
    STATE(29), 3,
      sym_verbatim,
      sym_bold,
      sym_italic,
    ACTIONS(11), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [39] = 5,
    ACTIONS(118), 1,
      anon_sym_COLON,
    ACTIONS(120), 1,
      sym__open_conflict,
    STATE(69), 1,
      sym_link_modifier,
    ACTIONS(116), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(114), 10,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [67] = 9,
    ACTIONS(82), 1,
      sym_word,
    ACTIONS(86), 1,
      anon_sym_STAR,
    ACTIONS(88), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_BQUOTE,
    STATE(19), 1,
      sym_italic_open,
    STATE(62), 1,
      sym_verbatim_open,
    STATE(10), 2,
      sym_punc,
      sym__bold_non_ws,
    STATE(25), 2,
      sym_verbatim,
      sym_italic,
    ACTIONS(84), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [102] = 9,
    ACTIONS(82), 1,
      sym_word,
    ACTIONS(86), 1,
      anon_sym_STAR,
    ACTIONS(88), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_BQUOTE,
    STATE(19), 1,
      sym_italic_open,
    STATE(62), 1,
      sym_verbatim_open,
    STATE(14), 2,
      sym_punc,
      sym__bold_non_ws,
    STATE(25), 2,
      sym_verbatim,
      sym_italic,
    ACTIONS(84), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [137] = 9,
    ACTIONS(66), 1,
      sym_word,
    ACTIONS(70), 1,
      anon_sym_STAR,
    ACTIONS(72), 1,
      anon_sym_SLASH,
    ACTIONS(74), 1,
      anon_sym_BQUOTE,
    STATE(20), 1,
      sym_bold_open,
    STATE(61), 1,
      sym_verbatim_open,
    STATE(7), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(27), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(68), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [172] = 9,
    ACTIONS(82), 1,
      sym_word,
    ACTIONS(86), 1,
      anon_sym_STAR,
    ACTIONS(88), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_BQUOTE,
    STATE(19), 1,
      sym_italic_open,
    STATE(62), 1,
      sym_verbatim_open,
    STATE(8), 2,
      sym_punc,
      sym__bold_non_ws,
    STATE(25), 2,
      sym_verbatim,
      sym_italic,
    ACTIONS(84), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [207] = 9,
    ACTIONS(66), 1,
      sym_word,
    ACTIONS(70), 1,
      anon_sym_STAR,
    ACTIONS(72), 1,
      anon_sym_SLASH,
    ACTIONS(74), 1,
      anon_sym_BQUOTE,
    STATE(20), 1,
      sym_bold_open,
    STATE(61), 1,
      sym_verbatim_open,
    STATE(13), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(27), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(68), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [242] = 4,
    ACTIONS(118), 1,
      anon_sym_COLON,
    STATE(79), 1,
      sym_link_modifier,
    ACTIONS(96), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(94), 10,
      sym__close_conflict,
      sym_italic_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [267] = 4,
    ACTIONS(118), 1,
      anon_sym_COLON,
    STATE(74), 1,
      sym_link_modifier,
    ACTIONS(100), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(98), 10,
      sym__close_conflict,
      sym_bold_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [292] = 4,
    ACTIONS(118), 1,
      anon_sym_COLON,
    STATE(70), 1,
      sym_link_modifier,
    ACTIONS(124), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(122), 10,
      sym__close_conflict,
      sym_bold_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [317] = 4,
    ACTIONS(118), 1,
      anon_sym_COLON,
    STATE(75), 1,
      sym_link_modifier,
    ACTIONS(124), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(122), 10,
      sym__close_conflict,
      sym_bold_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [342] = 4,
    ACTIONS(118), 1,
      anon_sym_COLON,
    STATE(71), 1,
      sym_link_modifier,
    ACTIONS(128), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(126), 10,
      sym__close_conflict,
      sym_italic_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [367] = 4,
    ACTIONS(118), 1,
      anon_sym_COLON,
    STATE(76), 1,
      sym_link_modifier,
    ACTIONS(128), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(126), 10,
      sym__close_conflict,
      sym_italic_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [392] = 4,
    ACTIONS(118), 1,
      anon_sym_COLON,
    STATE(77), 1,
      sym_link_modifier,
    ACTIONS(50), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(48), 10,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [417] = 4,
    ACTIONS(118), 1,
      anon_sym_COLON,
    STATE(73), 1,
      sym_link_modifier,
    ACTIONS(116), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(114), 10,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [442] = 9,
    ACTIONS(66), 1,
      sym_word,
    ACTIONS(70), 1,
      anon_sym_STAR,
    ACTIONS(72), 1,
      anon_sym_SLASH,
    ACTIONS(74), 1,
      anon_sym_BQUOTE,
    STATE(20), 1,
      sym_bold_open,
    STATE(61), 1,
      sym_verbatim_open,
    STATE(9), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(27), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(68), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [477] = 4,
    ACTIONS(132), 1,
      anon_sym_CR,
    ACTIONS(137), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(130), 4,
      sym_bold_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_ws,
    ACTIONS(134), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [501] = 2,
    ACTIONS(132), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(130), 11,
      sym__close_conflict,
      sym_bold_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [521] = 4,
    ACTIONS(132), 1,
      anon_sym_CR,
    ACTIONS(143), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(130), 4,
      sym__paragraph_break,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_ws,
    ACTIONS(140), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [545] = 4,
    ACTIONS(132), 1,
      anon_sym_CR,
    ACTIONS(137), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(130), 4,
      sym__paragraph_break,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_ws,
    ACTIONS(134), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [569] = 2,
    ACTIONS(132), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(130), 11,
      sym__close_conflict,
      sym_italic_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [589] = 2,
    ACTIONS(148), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(146), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [609] = 2,
    ACTIONS(148), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(146), 11,
      sym__close_conflict,
      sym_italic_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [629] = 4,
    ACTIONS(132), 1,
      anon_sym_CR,
    ACTIONS(153), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(130), 4,
      sym_italic_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_ws,
    ACTIONS(150), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [653] = 2,
    ACTIONS(50), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(48), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [673] = 2,
    ACTIONS(158), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(156), 11,
      sym__close_conflict,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [693] = 2,
    ACTIONS(162), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(160), 11,
      sym__close_conflict,
      sym_bold_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [713] = 2,
    ACTIONS(166), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(164), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [733] = 2,
    ACTIONS(132), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(130), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [753] = 2,
    ACTIONS(166), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(164), 11,
      sym__close_conflict,
      sym_italic_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [773] = 2,
    ACTIONS(148), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(146), 11,
      sym__close_conflict,
      sym_bold_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [793] = 2,
    ACTIONS(162), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(160), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [813] = 4,
    ACTIONS(132), 1,
      anon_sym_CR,
    ACTIONS(153), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(130), 4,
      sym_bold_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_ws,
    ACTIONS(150), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [837] = 4,
    ACTIONS(132), 1,
      anon_sym_CR,
    ACTIONS(143), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(130), 4,
      sym_italic_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_ws,
    ACTIONS(140), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [861] = 2,
    ACTIONS(170), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(168), 11,
      sym__close_conflict,
      sym_italic_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [881] = 2,
    ACTIONS(54), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(52), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [901] = 2,
    ACTIONS(100), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(98), 11,
      sym__close_conflict,
      sym_bold_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [921] = 2,
    ACTIONS(174), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(172), 11,
      sym__close_conflict,
      sym_bold_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [941] = 2,
    ACTIONS(178), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(176), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [961] = 2,
    ACTIONS(96), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(94), 11,
      sym__close_conflict,
      sym_italic_close,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [981] = 4,
    ACTIONS(132), 1,
      anon_sym_CR,
    ACTIONS(153), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(130), 4,
      sym__paragraph_break,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_ws,
    ACTIONS(150), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1005] = 3,
    STATE(60), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(182), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(180), 9,
      sym__close_conflict,
      sym_verbatim_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1026] = 6,
    ACTIONS(184), 1,
      sym_word,
    ACTIONS(186), 1,
      sym_ws,
    ACTIONS(192), 1,
      sym_verbatim_close,
    STATE(60), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(190), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(188), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1053] = 6,
    ACTIONS(184), 1,
      sym_word,
    ACTIONS(186), 1,
      sym_ws,
    ACTIONS(194), 1,
      sym_verbatim_close,
    STATE(60), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(190), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(188), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1080] = 6,
    ACTIONS(184), 1,
      sym_word,
    ACTIONS(186), 1,
      sym_ws,
    ACTIONS(196), 1,
      sym_verbatim_close,
    STATE(60), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(190), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(188), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1107] = 3,
    STATE(60), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(200), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(198), 9,
      sym__close_conflict,
      sym_verbatim_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1128] = 4,
    ACTIONS(202), 1,
      sym_word,
    STATE(57), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(190), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(188), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1149] = 4,
    ACTIONS(204), 1,
      sym_word,
    STATE(59), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(190), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(188), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1170] = 2,
    ACTIONS(132), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(130), 9,
      sym__close_conflict,
      sym_verbatim_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1187] = 4,
    ACTIONS(206), 1,
      sym_word,
    STATE(58), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(190), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(188), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1208] = 4,
    ACTIONS(208), 1,
      sym_word,
    STATE(56), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(190), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(188), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1229] = 2,
    ACTIONS(212), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(210), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1244] = 2,
    ACTIONS(216), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(214), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1259] = 2,
    ACTIONS(220), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(218), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1274] = 7,
    ACTIONS(222), 1,
      anon_sym_STAR,
    ACTIONS(224), 1,
      anon_sym_SLASH,
    ACTIONS(226), 1,
      anon_sym_BQUOTE,
    STATE(18), 1,
      sym_bold_open,
    STATE(21), 1,
      sym_italic_open,
    STATE(64), 1,
      sym_verbatim_open,
    STATE(28), 3,
      sym_verbatim,
      sym_bold,
      sym_italic,
  [1298] = 5,
    ACTIONS(224), 1,
      anon_sym_SLASH,
    ACTIONS(226), 1,
      anon_sym_BQUOTE,
    STATE(19), 1,
      sym_italic_open,
    STATE(62), 1,
      sym_verbatim_open,
    STATE(23), 2,
      sym_verbatim,
      sym_italic,
  [1315] = 5,
    ACTIONS(222), 1,
      anon_sym_STAR,
    ACTIONS(226), 1,
      anon_sym_BQUOTE,
    STATE(20), 1,
      sym_bold_open,
    STATE(61), 1,
      sym_verbatim_open,
    STATE(22), 2,
      sym_verbatim,
      sym_bold,
  [1332] = 1,
    ACTIONS(228), 4,
      sym_word,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
  [1339] = 1,
    ACTIONS(230), 1,
      sym_word,
  [1343] = 1,
    ACTIONS(232), 1,
      sym_word,
  [1347] = 1,
    ACTIONS(234), 1,
      sym_word,
  [1351] = 1,
    ACTIONS(236), 1,
      sym_word,
  [1355] = 1,
    ACTIONS(238), 1,
      sym_word,
  [1359] = 1,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
  [1363] = 1,
    ACTIONS(242), 1,
      sym_word,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(15)] = 0,
  [SMALL_STATE(16)] = 39,
  [SMALL_STATE(17)] = 67,
  [SMALL_STATE(18)] = 102,
  [SMALL_STATE(19)] = 137,
  [SMALL_STATE(20)] = 172,
  [SMALL_STATE(21)] = 207,
  [SMALL_STATE(22)] = 242,
  [SMALL_STATE(23)] = 267,
  [SMALL_STATE(24)] = 292,
  [SMALL_STATE(25)] = 317,
  [SMALL_STATE(26)] = 342,
  [SMALL_STATE(27)] = 367,
  [SMALL_STATE(28)] = 392,
  [SMALL_STATE(29)] = 417,
  [SMALL_STATE(30)] = 442,
  [SMALL_STATE(31)] = 477,
  [SMALL_STATE(32)] = 501,
  [SMALL_STATE(33)] = 521,
  [SMALL_STATE(34)] = 545,
  [SMALL_STATE(35)] = 569,
  [SMALL_STATE(36)] = 589,
  [SMALL_STATE(37)] = 609,
  [SMALL_STATE(38)] = 629,
  [SMALL_STATE(39)] = 653,
  [SMALL_STATE(40)] = 673,
  [SMALL_STATE(41)] = 693,
  [SMALL_STATE(42)] = 713,
  [SMALL_STATE(43)] = 733,
  [SMALL_STATE(44)] = 753,
  [SMALL_STATE(45)] = 773,
  [SMALL_STATE(46)] = 793,
  [SMALL_STATE(47)] = 813,
  [SMALL_STATE(48)] = 837,
  [SMALL_STATE(49)] = 861,
  [SMALL_STATE(50)] = 881,
  [SMALL_STATE(51)] = 901,
  [SMALL_STATE(52)] = 921,
  [SMALL_STATE(53)] = 941,
  [SMALL_STATE(54)] = 961,
  [SMALL_STATE(55)] = 981,
  [SMALL_STATE(56)] = 1005,
  [SMALL_STATE(57)] = 1026,
  [SMALL_STATE(58)] = 1053,
  [SMALL_STATE(59)] = 1080,
  [SMALL_STATE(60)] = 1107,
  [SMALL_STATE(61)] = 1128,
  [SMALL_STATE(62)] = 1149,
  [SMALL_STATE(63)] = 1170,
  [SMALL_STATE(64)] = 1187,
  [SMALL_STATE(65)] = 1208,
  [SMALL_STATE(66)] = 1229,
  [SMALL_STATE(67)] = 1244,
  [SMALL_STATE(68)] = 1259,
  [SMALL_STATE(69)] = 1274,
  [SMALL_STATE(70)] = 1298,
  [SMALL_STATE(71)] = 1315,
  [SMALL_STATE(72)] = 1332,
  [SMALL_STATE(73)] = 1339,
  [SMALL_STATE(74)] = 1343,
  [SMALL_STATE(75)] = 1347,
  [SMALL_STATE(76)] = 1351,
  [SMALL_STATE(77)] = 1355,
  [SMALL_STATE(78)] = 1359,
  [SMALL_STATE(79)] = 1363,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(3),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(3),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(16),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(43),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(33),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(34),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(55),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__non_ws, 3),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__non_ws, 3),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__non_ws, 2),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__non_ws, 2),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__italic_non_ws, 3),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__italic_non_ws, 3),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bold_non_ws, 3),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bold_non_ws, 3),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__italic_non_ws, 2),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__italic_non_ws, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bold_non_ws, 2),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bold_non_ws, 2),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__non_ws, 1),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__non_ws, 1),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bold_non_ws, 1),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bold_non_ws, 1),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__italic_non_ws, 1),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__italic_non_ws, 1),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_punc, 1),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_punc, 1),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_punc, 1), REDUCE(sym_italic_open, 1),
  [137] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_punc, 1), REDUCE(sym_italic_open, 1),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_punc, 1), REDUCE(sym_bold_open, 1),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_punc, 1), REDUCE(sym_bold_open, 1),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim, 3, .dynamic_precedence = 2),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim, 3, .dynamic_precedence = 2),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_punc, 1), REDUCE(sym_verbatim_open, 1),
  [153] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_punc, 1), REDUCE(sym_verbatim_open, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3, .dynamic_precedence = 1),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 3, .dynamic_precedence = 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3, .dynamic_precedence = 1),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold, 3, .dynamic_precedence = 1),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__italic_non_ws, 5),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__italic_non_ws, 5),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bold_non_ws, 5),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bold_non_ws, 5),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__non_ws, 5),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__non_ws, 5),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__verbatim_non_ws, 3),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__verbatim_non_ws, 3),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__verbatim_non_ws, 2),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__verbatim_non_ws, 2),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_open, 1),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_open, 1),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold_open, 1),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold_open, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic_open, 1),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic_open, 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_modifier, 1, .dynamic_precedence = 1),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [240] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__paragraph_break = 0,
  ts_external_token__open_conflict = 1,
  ts_external_token__close_conflict = 2,
  ts_external_token_bold_close = 3,
  ts_external_token_italic_close = 4,
  ts_external_token_verbatim_close = 5,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__paragraph_break] = sym__paragraph_break,
  [ts_external_token__open_conflict] = sym__open_conflict,
  [ts_external_token__close_conflict] = sym__close_conflict,
  [ts_external_token_bold_close] = sym_bold_close,
  [ts_external_token_italic_close] = sym_italic_close,
  [ts_external_token_verbatim_close] = sym_verbatim_close,
};

static const bool ts_external_scanner_states[8][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__paragraph_break] = true,
    [ts_external_token__open_conflict] = true,
    [ts_external_token__close_conflict] = true,
    [ts_external_token_bold_close] = true,
    [ts_external_token_italic_close] = true,
    [ts_external_token_verbatim_close] = true,
  },
  [2] = {
    [ts_external_token__close_conflict] = true,
  },
  [3] = {
    [ts_external_token__paragraph_break] = true,
    [ts_external_token__close_conflict] = true,
  },
  [4] = {
    [ts_external_token__close_conflict] = true,
    [ts_external_token_italic_close] = true,
  },
  [5] = {
    [ts_external_token__close_conflict] = true,
    [ts_external_token_bold_close] = true,
  },
  [6] = {
    [ts_external_token__paragraph_break] = true,
    [ts_external_token__open_conflict] = true,
    [ts_external_token__close_conflict] = true,
  },
  [7] = {
    [ts_external_token__close_conflict] = true,
    [ts_external_token_verbatim_close] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_norgtest_external_scanner_create(void);
void tree_sitter_norgtest_external_scanner_destroy(void *);
bool tree_sitter_norgtest_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_norgtest_external_scanner_serialize(void *, char *);
void tree_sitter_norgtest_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_norgtest(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_norgtest_external_scanner_create,
      tree_sitter_norgtest_external_scanner_destroy,
      tree_sitter_norgtest_external_scanner_scan,
      tree_sitter_norgtest_external_scanner_serialize,
      tree_sitter_norgtest_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
