#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_CR = 2,
  anon_sym_CR_LF = 3,
  anon_sym_NULL = 4,
  sym_word = 5,
  aux_sym_punc_token1 = 6,
  aux_sym_punc_token2 = 7,
  aux_sym_punc_token3 = 8,
  anon_sym_STAR = 9,
  anon_sym_SLASH = 10,
  anon_sym_BQUOTE = 11,
  anon_sym_DOT = 12,
  sym_document = 13,
  sym_paragraph = 14,
  sym_punc = 15,
  sym_bold_open = 16,
  sym_italic_open = 17,
  sym_verbatim_open = 18,
  sym_bold_close = 19,
  sym_italic_close = 20,
  sym_verbatim_close = 21,
  sym_bold = 22,
  sym_italic = 23,
  sym_verbatim = 24,
  aux_sym_document_repeat1 = 25,
  aux_sym_paragraph_repeat1 = 26,
  aux_sym_bold_repeat1 = 27,
  aux_sym_italic_repeat1 = 28,
  aux_sym_verbatim_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_CR] = "\r",
  [anon_sym_CR_LF] = "\r\n",
  [anon_sym_NULL] = "\0",
  [sym_word] = "word",
  [aux_sym_punc_token1] = "punc_token1",
  [aux_sym_punc_token2] = "punc_token2",
  [aux_sym_punc_token3] = "punc_token3",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_DOT] = ".",
  [sym_document] = "document",
  [sym_paragraph] = "paragraph",
  [sym_punc] = "punc",
  [sym_bold_open] = "_open",
  [sym_italic_open] = "_open",
  [sym_verbatim_open] = "_open",
  [sym_bold_close] = "bold_close",
  [sym_italic_close] = "_close",
  [sym_verbatim_close] = "_close",
  [sym_bold] = "bold",
  [sym_italic] = "italic",
  [sym_verbatim] = "verbatim",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_bold_repeat1] = "bold_repeat1",
  [aux_sym_italic_repeat1] = "italic_repeat1",
  [aux_sym_verbatim_repeat1] = "verbatim_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_CR] = anon_sym_CR,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [anon_sym_NULL] = anon_sym_NULL,
  [sym_word] = sym_word,
  [aux_sym_punc_token1] = aux_sym_punc_token1,
  [aux_sym_punc_token2] = aux_sym_punc_token2,
  [aux_sym_punc_token3] = aux_sym_punc_token3,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_document] = sym_document,
  [sym_paragraph] = sym_paragraph,
  [sym_punc] = sym_punc,
  [sym_bold_open] = sym_bold_open,
  [sym_italic_open] = sym_bold_open,
  [sym_verbatim_open] = sym_bold_open,
  [sym_bold_close] = sym_bold_close,
  [sym_italic_close] = sym_italic_close,
  [sym_verbatim_close] = sym_italic_close,
  [sym_bold] = sym_bold,
  [sym_italic] = sym_italic,
  [sym_verbatim] = sym_verbatim,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_bold_repeat1] = aux_sym_bold_repeat1,
  [aux_sym_italic_repeat1] = aux_sym_italic_repeat1,
  [aux_sym_verbatim_repeat1] = aux_sym_verbatim_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NULL] = {
    .visible = true,
    .named = false,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_punc_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_punc_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_punc_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_punc] = {
    .visible = true,
    .named = true,
  },
  [sym_bold_open] = {
    .visible = true,
    .named = true,
  },
  [sym_italic_open] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_open] = {
    .visible = true,
    .named = true,
  },
  [sym_bold_close] = {
    .visible = true,
    .named = true,
  },
  [sym_italic_close] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_close] = {
    .visible = true,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bold_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_italic_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_verbatim_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [2] = sym_italic_close,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_bold_close, 2,
    sym_bold_close,
    sym_italic_close,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (!eof && lookahead == 0) ADVANCE(8);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '*') ADVANCE(13);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '`') ADVANCE(15);
      if (lookahead == 'w') ADVANCE(2);
      END_STATE();
    case 1:
      if (lookahead == 'd') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(1);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_CR);
      if (lookahead == '\n') ADVANCE(7);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_CR_LF);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_NULL);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_word);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_punc_token1);
      if (lookahead == '*') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_punc_token2);
      if (lookahead == '/') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_punc_token3);
      if (lookahead == '`') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(10);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(11);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == '`') ADVANCE(12);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_CR] = ACTIONS(1),
    [anon_sym_CR_LF] = ACTIONS(1),
    [anon_sym_NULL] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [aux_sym_punc_token1] = ACTIONS(1),
    [aux_sym_punc_token2] = ACTIONS(1),
    [aux_sym_punc_token3] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(25),
    [sym_paragraph] = STATE(3),
    [sym_punc] = STATE(5),
    [sym_bold_open] = STATE(10),
    [sym_italic_open] = STATE(11),
    [sym_verbatim_open] = STATE(23),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_verbatim] = STATE(5),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [anon_sym_LF] = ACTIONS(3),
    [anon_sym_CR] = ACTIONS(5),
    [anon_sym_CR_LF] = ACTIONS(3),
    [anon_sym_NULL] = ACTIONS(3),
    [sym_word] = ACTIONS(7),
    [aux_sym_punc_token1] = ACTIONS(9),
    [aux_sym_punc_token2] = ACTIONS(9),
    [aux_sym_punc_token3] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(9),
  },
  [2] = {
    [sym_paragraph] = STATE(2),
    [sym_punc] = STATE(5),
    [sym_bold_open] = STATE(10),
    [sym_italic_open] = STATE(11),
    [sym_verbatim_open] = STATE(23),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_verbatim] = STATE(5),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_LF] = ACTIONS(19),
    [anon_sym_CR] = ACTIONS(22),
    [anon_sym_CR_LF] = ACTIONS(19),
    [anon_sym_NULL] = ACTIONS(19),
    [sym_word] = ACTIONS(25),
    [aux_sym_punc_token1] = ACTIONS(28),
    [aux_sym_punc_token2] = ACTIONS(28),
    [aux_sym_punc_token3] = ACTIONS(28),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(34),
    [anon_sym_BQUOTE] = ACTIONS(37),
    [anon_sym_DOT] = ACTIONS(28),
  },
  [3] = {
    [sym_paragraph] = STATE(2),
    [sym_punc] = STATE(5),
    [sym_bold_open] = STATE(10),
    [sym_italic_open] = STATE(11),
    [sym_verbatim_open] = STATE(23),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_verbatim] = STATE(5),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(40),
    [anon_sym_LF] = ACTIONS(42),
    [anon_sym_CR] = ACTIONS(44),
    [anon_sym_CR_LF] = ACTIONS(42),
    [anon_sym_NULL] = ACTIONS(42),
    [sym_word] = ACTIONS(7),
    [aux_sym_punc_token1] = ACTIONS(9),
    [aux_sym_punc_token2] = ACTIONS(9),
    [aux_sym_punc_token3] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(9),
  },
  [4] = {
    [sym_punc] = STATE(4),
    [sym_bold_open] = STATE(10),
    [sym_italic_open] = STATE(11),
    [sym_verbatim_open] = STATE(23),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_verbatim] = STATE(4),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(46),
    [anon_sym_LF] = ACTIONS(46),
    [anon_sym_CR] = ACTIONS(48),
    [anon_sym_CR_LF] = ACTIONS(46),
    [anon_sym_NULL] = ACTIONS(46),
    [sym_word] = ACTIONS(50),
    [aux_sym_punc_token1] = ACTIONS(53),
    [aux_sym_punc_token2] = ACTIONS(53),
    [aux_sym_punc_token3] = ACTIONS(53),
    [anon_sym_STAR] = ACTIONS(56),
    [anon_sym_SLASH] = ACTIONS(59),
    [anon_sym_BQUOTE] = ACTIONS(62),
    [anon_sym_DOT] = ACTIONS(53),
  },
  [5] = {
    [sym_punc] = STATE(4),
    [sym_bold_open] = STATE(10),
    [sym_italic_open] = STATE(11),
    [sym_verbatim_open] = STATE(23),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_verbatim] = STATE(4),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(65),
    [anon_sym_LF] = ACTIONS(65),
    [anon_sym_CR] = ACTIONS(67),
    [anon_sym_CR_LF] = ACTIONS(65),
    [anon_sym_NULL] = ACTIONS(65),
    [sym_word] = ACTIONS(69),
    [aux_sym_punc_token1] = ACTIONS(9),
    [aux_sym_punc_token2] = ACTIONS(9),
    [aux_sym_punc_token3] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(13), 1,
      anon_sym_SLASH,
    ACTIONS(15), 1,
      anon_sym_BQUOTE,
    ACTIONS(71), 1,
      sym_word,
    ACTIONS(73), 1,
      anon_sym_STAR,
    STATE(11), 1,
      sym_italic_open,
    STATE(12), 1,
      sym_bold_close,
    STATE(23), 1,
      sym_verbatim_open,
    ACTIONS(9), 4,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
    STATE(9), 4,
      sym_punc,
      sym_italic,
      sym_verbatim,
      aux_sym_bold_repeat1,
  [34] = 9,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      anon_sym_BQUOTE,
    ACTIONS(75), 1,
      sym_word,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    STATE(10), 1,
      sym_bold_open,
    STATE(18), 1,
      sym_italic_close,
    STATE(23), 1,
      sym_verbatim_open,
    ACTIONS(9), 4,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
    STATE(8), 4,
      sym_punc,
      sym_bold,
      sym_verbatim,
      aux_sym_italic_repeat1,
  [68] = 8,
    ACTIONS(79), 1,
      sym_word,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(88), 1,
      anon_sym_SLASH,
    ACTIONS(91), 1,
      anon_sym_BQUOTE,
    STATE(10), 1,
      sym_bold_open,
    STATE(23), 1,
      sym_verbatim_open,
    ACTIONS(82), 4,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
    STATE(8), 4,
      sym_punc,
      sym_bold,
      sym_verbatim,
      aux_sym_italic_repeat1,
  [99] = 8,
    ACTIONS(94), 1,
      sym_word,
    ACTIONS(100), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_SLASH,
    ACTIONS(106), 1,
      anon_sym_BQUOTE,
    STATE(11), 1,
      sym_italic_open,
    STATE(23), 1,
      sym_verbatim_open,
    ACTIONS(97), 4,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
    STATE(9), 4,
      sym_punc,
      sym_italic,
      sym_verbatim,
      aux_sym_bold_repeat1,
  [130] = 8,
    ACTIONS(13), 1,
      anon_sym_SLASH,
    ACTIONS(15), 1,
      anon_sym_BQUOTE,
    ACTIONS(109), 1,
      sym_word,
    ACTIONS(111), 1,
      anon_sym_STAR,
    STATE(11), 1,
      sym_italic_open,
    STATE(23), 1,
      sym_verbatim_open,
    ACTIONS(9), 4,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
    STATE(6), 4,
      sym_punc,
      sym_italic,
      sym_verbatim,
      aux_sym_bold_repeat1,
  [161] = 8,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      anon_sym_BQUOTE,
    ACTIONS(111), 1,
      anon_sym_SLASH,
    ACTIONS(113), 1,
      sym_word,
    STATE(10), 1,
      sym_bold_open,
    STATE(23), 1,
      sym_verbatim_open,
    ACTIONS(9), 4,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
    STATE(7), 4,
      sym_punc,
      sym_bold,
      sym_verbatim,
      aux_sym_italic_repeat1,
  [192] = 2,
    ACTIONS(117), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(115), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [210] = 2,
    ACTIONS(121), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(119), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [228] = 2,
    ACTIONS(125), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(123), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [246] = 4,
    ACTIONS(121), 1,
      anon_sym_CR,
    ACTIONS(130), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(119), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
    ACTIONS(127), 5,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [268] = 4,
    ACTIONS(121), 1,
      anon_sym_CR,
    ACTIONS(136), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(119), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
    ACTIONS(133), 5,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [290] = 2,
    ACTIONS(141), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(139), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [308] = 2,
    ACTIONS(145), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(143), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [326] = 4,
    ACTIONS(121), 1,
      anon_sym_CR,
    ACTIONS(150), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(119), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
    ACTIONS(147), 5,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [348] = 2,
    ACTIONS(155), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(153), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [366] = 2,
    ACTIONS(159), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(157), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [384] = 6,
    ACTIONS(161), 1,
      sym_word,
    ACTIONS(163), 1,
      anon_sym_BQUOTE,
    STATE(21), 1,
      sym_verbatim_close,
    ACTIONS(111), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(24), 2,
      sym_punc,
      aux_sym_verbatim_repeat1,
    ACTIONS(9), 4,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [408] = 4,
    ACTIONS(165), 1,
      sym_word,
    STATE(22), 2,
      sym_punc,
      aux_sym_verbatim_repeat1,
    ACTIONS(111), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(9), 4,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [427] = 4,
    ACTIONS(167), 1,
      sym_word,
    STATE(24), 2,
      sym_punc,
      aux_sym_verbatim_repeat1,
    ACTIONS(173), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(170), 4,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [446] = 1,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 34,
  [SMALL_STATE(8)] = 68,
  [SMALL_STATE(9)] = 99,
  [SMALL_STATE(10)] = 130,
  [SMALL_STATE(11)] = 161,
  [SMALL_STATE(12)] = 192,
  [SMALL_STATE(13)] = 210,
  [SMALL_STATE(14)] = 228,
  [SMALL_STATE(15)] = 246,
  [SMALL_STATE(16)] = 268,
  [SMALL_STATE(17)] = 290,
  [SMALL_STATE(18)] = 308,
  [SMALL_STATE(19)] = 326,
  [SMALL_STATE(20)] = 348,
  [SMALL_STATE(21)] = 366,
  [SMALL_STATE(22)] = 384,
  [SMALL_STATE(23)] = 408,
  [SMALL_STATE(24)] = 427,
  [SMALL_STATE(25)] = 446,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(2),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(5),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(13),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(19),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(16),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(15),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(4),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(13),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(19),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(16),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(15),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 1),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2), SHIFT_REPEAT(8),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2), SHIFT_REPEAT(13),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_italic_repeat1, 2), SHIFT_REPEAT(19),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_italic_repeat1, 2), SHIFT_REPEAT(13),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_italic_repeat1, 2), SHIFT_REPEAT(15),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2), SHIFT_REPEAT(9),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2), SHIFT_REPEAT(13),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_bold_repeat1, 2), SHIFT_REPEAT(13),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_bold_repeat1, 2), SHIFT_REPEAT(16),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_bold_repeat1, 2), SHIFT_REPEAT(15),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3, .dynamic_precedence = 1, .production_id = 1),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold, 3, .dynamic_precedence = 1, .production_id = 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_punc, 1),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_punc, 1),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold_close, 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold_close, 1),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_punc, 1), REDUCE(sym_verbatim_open, 1),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_punc, 1), REDUCE(sym_verbatim_open, 1),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_punc, 1), REDUCE(sym_italic_open, 1),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_punc, 1), REDUCE(sym_italic_open, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic_close, 1),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic_close, 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3, .dynamic_precedence = 1),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 3, .dynamic_precedence = 1),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_punc, 1), REDUCE(sym_bold_open, 1),
  [150] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_punc, 1), REDUCE(sym_bold_open, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_close, 1),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_close, 1),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim, 3, .dynamic_precedence = 2),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim, 3, .dynamic_precedence = 2),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_verbatim_repeat1, 2), SHIFT_REPEAT(24),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_verbatim_repeat1, 2), SHIFT_REPEAT(13),
  [173] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_verbatim_repeat1, 2), SHIFT_REPEAT(13),
  [176] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_norgtest(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
