#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 114
#define LARGE_STATE_COUNT 12
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 6
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_CR = 2,
  anon_sym_CR_LF = 3,
  anon_sym_NULL = 4,
  sym_word = 5,
  sym_ws = 6,
  aux_sym_punc_token1 = 7,
  aux_sym_punc_token2 = 8,
  aux_sym_punc_token3 = 9,
  anon_sym_STAR = 10,
  anon_sym_SLASH = 11,
  anon_sym_BQUOTE = 12,
  anon_sym_DOT = 13,
  anon_sym_COLON = 14,
  sym__paragraph_break = 15,
  sym__open_conflict = 16,
  sym__close_conflict = 17,
  sym_bold_close = 18,
  sym_italic_close = 19,
  sym_verbatim_close = 20,
  sym_document = 21,
  sym_paragraph = 22,
  sym_punc = 23,
  sym_link_modifier = 24,
  sym_verbatim_open = 25,
  sym_verbatim = 26,
  sym__verbatim_non_ws = 27,
  sym_bold_open = 28,
  sym__bold_non_ws = 29,
  sym_bold = 30,
  sym_italic_open = 31,
  sym__italic_non_ws = 32,
  sym_italic = 33,
  sym__non_ws = 34,
  sym__newline_non_ws = 35,
  aux_sym_document_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_CR] = "\r",
  [anon_sym_CR_LF] = "\r\n",
  [anon_sym_NULL] = "\0",
  [sym_word] = "word",
  [sym_ws] = "ws",
  [aux_sym_punc_token1] = "punc_token1",
  [aux_sym_punc_token2] = "punc_token2",
  [aux_sym_punc_token3] = "punc_token3",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_DOT] = ".",
  [anon_sym_COLON] = ":",
  [sym__paragraph_break] = "_paragraph_break",
  [sym__open_conflict] = "punc",
  [sym__close_conflict] = "_close_conflict",
  [sym_bold_close] = "bold_close",
  [sym_italic_close] = "italic_close",
  [sym_verbatim_close] = "verbatim_close",
  [sym_document] = "document",
  [sym_paragraph] = "paragraph",
  [sym_punc] = "punc",
  [sym_link_modifier] = "link_modifier",
  [sym_verbatim_open] = "verbatim_open",
  [sym_verbatim] = "verbatim",
  [sym__verbatim_non_ws] = "_verbatim_non_ws",
  [sym_bold_open] = "bold_open",
  [sym__bold_non_ws] = "_bold_non_ws",
  [sym_bold] = "bold",
  [sym_italic_open] = "italic_open",
  [sym__italic_non_ws] = "_italic_non_ws",
  [sym_italic] = "italic",
  [sym__non_ws] = "_non_ws",
  [sym__newline_non_ws] = "_newline_non_ws",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_CR] = anon_sym_CR,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [anon_sym_NULL] = anon_sym_NULL,
  [sym_word] = sym_word,
  [sym_ws] = sym_ws,
  [aux_sym_punc_token1] = aux_sym_punc_token1,
  [aux_sym_punc_token2] = aux_sym_punc_token2,
  [aux_sym_punc_token3] = aux_sym_punc_token3,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym__paragraph_break] = sym__paragraph_break,
  [sym__open_conflict] = sym_punc,
  [sym__close_conflict] = sym__close_conflict,
  [sym_bold_close] = sym_bold_close,
  [sym_italic_close] = sym_italic_close,
  [sym_verbatim_close] = sym_verbatim_close,
  [sym_document] = sym_document,
  [sym_paragraph] = sym_paragraph,
  [sym_punc] = sym_punc,
  [sym_link_modifier] = sym_link_modifier,
  [sym_verbatim_open] = sym_verbatim_open,
  [sym_verbatim] = sym_verbatim,
  [sym__verbatim_non_ws] = sym__verbatim_non_ws,
  [sym_bold_open] = sym_bold_open,
  [sym__bold_non_ws] = sym__bold_non_ws,
  [sym_bold] = sym_bold,
  [sym_italic_open] = sym_italic_open,
  [sym__italic_non_ws] = sym__italic_non_ws,
  [sym_italic] = sym_italic,
  [sym__non_ws] = sym__non_ws,
  [sym__newline_non_ws] = sym__newline_non_ws,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NULL] = {
    .visible = true,
    .named = false,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_ws] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_punc_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_punc_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_punc_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym__paragraph_break] = {
    .visible = false,
    .named = true,
  },
  [sym__open_conflict] = {
    .visible = true,
    .named = true,
  },
  [sym__close_conflict] = {
    .visible = false,
    .named = true,
  },
  [sym_bold_close] = {
    .visible = true,
    .named = true,
  },
  [sym_italic_close] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_close] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_punc] = {
    .visible = true,
    .named = true,
  },
  [sym_link_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_open] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim] = {
    .visible = true,
    .named = true,
  },
  [sym__verbatim_non_ws] = {
    .visible = false,
    .named = true,
  },
  [sym_bold_open] = {
    .visible = true,
    .named = true,
  },
  [sym__bold_non_ws] = {
    .visible = false,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic_open] = {
    .visible = true,
    .named = true,
  },
  [sym__italic_non_ws] = {
    .visible = false,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym__non_ws] = {
    .visible = false,
    .named = true,
  },
  [sym__newline_non_ws] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 8,
  [10] = 8,
  [11] = 8,
  [12] = 12,
  [13] = 13,
  [14] = 12,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 16,
  [20] = 20,
  [21] = 18,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 26,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 42,
  [46] = 42,
  [47] = 47,
  [48] = 48,
  [49] = 48,
  [50] = 50,
  [51] = 51,
  [52] = 51,
  [53] = 53,
  [54] = 50,
  [55] = 55,
  [56] = 41,
  [57] = 57,
  [58] = 51,
  [59] = 31,
  [60] = 48,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 41,
  [65] = 36,
  [66] = 66,
  [67] = 33,
  [68] = 40,
  [69] = 69,
  [70] = 31,
  [71] = 61,
  [72] = 31,
  [73] = 40,
  [74] = 30,
  [75] = 33,
  [76] = 66,
  [77] = 77,
  [78] = 36,
  [79] = 63,
  [80] = 66,
  [81] = 41,
  [82] = 61,
  [83] = 63,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 89,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 34,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 95,
  [102] = 102,
  [103] = 100,
  [104] = 95,
  [105] = 100,
  [106] = 102,
  [107] = 95,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 102,
  [112] = 112,
  [113] = 113,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (!eof && lookahead == 0) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead == ' ') ADVANCE(11);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == ':') ADVANCE(22);
      if (lookahead == '`') ADVANCE(20);
      if (lookahead == 'w') ADVANCE(3);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '`') ADVANCE(19);
      if (lookahead == 'w') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'd') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(2);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_CR);
      if (lookahead == '\n') ADVANCE(8);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_CR_LF);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_NULL);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_word);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_ws);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_punc_token1);
      if (lookahead == '*') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_punc_token2);
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_punc_token3);
      if (lookahead == '`') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(12);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == '`') ADVANCE(14);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 4},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 5},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 5},
  [17] = {.lex_state = 0, .external_lex_state = 4},
  [18] = {.lex_state = 0, .external_lex_state = 5},
  [19] = {.lex_state = 0, .external_lex_state = 5},
  [20] = {.lex_state = 0, .external_lex_state = 4},
  [21] = {.lex_state = 0, .external_lex_state = 4},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 6},
  [24] = {.lex_state = 0, .external_lex_state = 3},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0, .external_lex_state = 3},
  [30] = {.lex_state = 0, .external_lex_state = 3},
  [31] = {.lex_state = 0, .external_lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 3},
  [33] = {.lex_state = 0, .external_lex_state = 3},
  [34] = {.lex_state = 0, .external_lex_state = 3},
  [35] = {.lex_state = 0, .external_lex_state = 3},
  [36] = {.lex_state = 0, .external_lex_state = 3},
  [37] = {.lex_state = 0, .external_lex_state = 3},
  [38] = {.lex_state = 0, .external_lex_state = 3},
  [39] = {.lex_state = 0, .external_lex_state = 2},
  [40] = {.lex_state = 0, .external_lex_state = 3},
  [41] = {.lex_state = 0, .external_lex_state = 3},
  [42] = {.lex_state = 0, .external_lex_state = 7},
  [43] = {.lex_state = 0, .external_lex_state = 7},
  [44] = {.lex_state = 0, .external_lex_state = 7},
  [45] = {.lex_state = 0, .external_lex_state = 7},
  [46] = {.lex_state = 0, .external_lex_state = 7},
  [47] = {.lex_state = 0, .external_lex_state = 4},
  [48] = {.lex_state = 0, .external_lex_state = 4},
  [49] = {.lex_state = 0, .external_lex_state = 5},
  [50] = {.lex_state = 0, .external_lex_state = 4},
  [51] = {.lex_state = 0, .external_lex_state = 5},
  [52] = {.lex_state = 0, .external_lex_state = 4},
  [53] = {.lex_state = 0, .external_lex_state = 4},
  [54] = {.lex_state = 0, .external_lex_state = 5},
  [55] = {.lex_state = 0, .external_lex_state = 4},
  [56] = {.lex_state = 0, .external_lex_state = 4},
  [57] = {.lex_state = 0, .external_lex_state = 4},
  [58] = {.lex_state = 0, .external_lex_state = 2},
  [59] = {.lex_state = 0, .external_lex_state = 5},
  [60] = {.lex_state = 0, .external_lex_state = 2},
  [61] = {.lex_state = 0, .external_lex_state = 4},
  [62] = {.lex_state = 0, .external_lex_state = 4},
  [63] = {.lex_state = 0, .external_lex_state = 4},
  [64] = {.lex_state = 0, .external_lex_state = 5},
  [65] = {.lex_state = 0, .external_lex_state = 5},
  [66] = {.lex_state = 0, .external_lex_state = 2},
  [67] = {.lex_state = 0, .external_lex_state = 5},
  [68] = {.lex_state = 0, .external_lex_state = 5},
  [69] = {.lex_state = 0, .external_lex_state = 4},
  [70] = {.lex_state = 0, .external_lex_state = 4},
  [71] = {.lex_state = 0, .external_lex_state = 5},
  [72] = {.lex_state = 0, .external_lex_state = 7},
  [73] = {.lex_state = 0, .external_lex_state = 4},
  [74] = {.lex_state = 0, .external_lex_state = 4},
  [75] = {.lex_state = 0, .external_lex_state = 4},
  [76] = {.lex_state = 0, .external_lex_state = 2},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 0, .external_lex_state = 4},
  [79] = {.lex_state = 0, .external_lex_state = 5},
  [80] = {.lex_state = 0, .external_lex_state = 2},
  [81] = {.lex_state = 0, .external_lex_state = 2},
  [82] = {.lex_state = 0, .external_lex_state = 2},
  [83] = {.lex_state = 0, .external_lex_state = 2},
  [84] = {.lex_state = 0, .external_lex_state = 2},
  [85] = {.lex_state = 0, .external_lex_state = 2},
  [86] = {.lex_state = 0, .external_lex_state = 2},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 0, .external_lex_state = 8},
  [93] = {.lex_state = 0, .external_lex_state = 8},
  [94] = {.lex_state = 0, .external_lex_state = 8},
  [95] = {.lex_state = 0, .external_lex_state = 8},
  [96] = {.lex_state = 0, .external_lex_state = 8},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0, .external_lex_state = 8},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0, .external_lex_state = 8},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0, .external_lex_state = 8},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0, .external_lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_CR] = ACTIONS(1),
    [anon_sym_CR_LF] = ACTIONS(1),
    [anon_sym_NULL] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_ws] = ACTIONS(1),
    [aux_sym_punc_token1] = ACTIONS(1),
    [aux_sym_punc_token2] = ACTIONS(1),
    [aux_sym_punc_token3] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym__paragraph_break] = ACTIONS(1),
    [sym__open_conflict] = ACTIONS(1),
    [sym__close_conflict] = ACTIONS(1),
    [sym_bold_close] = ACTIONS(1),
    [sym_italic_close] = ACTIONS(1),
    [sym_verbatim_close] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(97),
    [sym_paragraph] = STATE(3),
    [sym_punc] = STATE(4),
    [sym_verbatim_open] = STATE(66),
    [sym_verbatim] = STATE(29),
    [sym_bold_open] = STATE(10),
    [sym_bold] = STATE(29),
    [sym_italic_open] = STATE(26),
    [sym_italic] = STATE(29),
    [sym__non_ws] = STATE(4),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_CR] = ACTIONS(7),
    [anon_sym_CR_LF] = ACTIONS(5),
    [anon_sym_NULL] = ACTIONS(5),
    [sym_word] = ACTIONS(9),
    [aux_sym_punc_token1] = ACTIONS(11),
    [aux_sym_punc_token2] = ACTIONS(11),
    [aux_sym_punc_token3] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(11),
    [sym__close_conflict] = ACTIONS(11),
  },
  [2] = {
    [sym_paragraph] = STATE(2),
    [sym_punc] = STATE(4),
    [sym_verbatim_open] = STATE(66),
    [sym_verbatim] = STATE(29),
    [sym_bold_open] = STATE(10),
    [sym_bold] = STATE(29),
    [sym_italic_open] = STATE(26),
    [sym_italic] = STATE(29),
    [sym__non_ws] = STATE(4),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_LF] = ACTIONS(21),
    [anon_sym_CR] = ACTIONS(24),
    [anon_sym_CR_LF] = ACTIONS(21),
    [anon_sym_NULL] = ACTIONS(21),
    [sym_word] = ACTIONS(27),
    [aux_sym_punc_token1] = ACTIONS(30),
    [aux_sym_punc_token2] = ACTIONS(30),
    [aux_sym_punc_token3] = ACTIONS(30),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(36),
    [anon_sym_BQUOTE] = ACTIONS(39),
    [anon_sym_DOT] = ACTIONS(30),
    [anon_sym_COLON] = ACTIONS(30),
    [sym__close_conflict] = ACTIONS(30),
  },
  [3] = {
    [sym_paragraph] = STATE(2),
    [sym_punc] = STATE(4),
    [sym_verbatim_open] = STATE(66),
    [sym_verbatim] = STATE(29),
    [sym_bold_open] = STATE(10),
    [sym_bold] = STATE(29),
    [sym_italic_open] = STATE(26),
    [sym_italic] = STATE(29),
    [sym__non_ws] = STATE(4),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(42),
    [anon_sym_LF] = ACTIONS(44),
    [anon_sym_CR] = ACTIONS(46),
    [anon_sym_CR_LF] = ACTIONS(44),
    [anon_sym_NULL] = ACTIONS(44),
    [sym_word] = ACTIONS(9),
    [aux_sym_punc_token1] = ACTIONS(11),
    [aux_sym_punc_token2] = ACTIONS(11),
    [aux_sym_punc_token3] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(11),
    [sym__close_conflict] = ACTIONS(11),
  },
  [4] = {
    [sym_punc] = STATE(7),
    [sym_verbatim_open] = STATE(66),
    [sym_verbatim] = STATE(29),
    [sym_bold_open] = STATE(10),
    [sym_bold] = STATE(29),
    [sym_italic_open] = STATE(26),
    [sym_italic] = STATE(29),
    [sym__non_ws] = STATE(7),
    [sym__newline_non_ws] = STATE(32),
    [anon_sym_LF] = ACTIONS(48),
    [anon_sym_CR] = ACTIONS(50),
    [anon_sym_CR_LF] = ACTIONS(48),
    [sym_word] = ACTIONS(9),
    [sym_ws] = ACTIONS(52),
    [aux_sym_punc_token1] = ACTIONS(11),
    [aux_sym_punc_token2] = ACTIONS(11),
    [aux_sym_punc_token3] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(11),
    [sym__paragraph_break] = ACTIONS(54),
    [sym__close_conflict] = ACTIONS(11),
  },
  [5] = {
    [sym_punc] = STATE(7),
    [sym_verbatim_open] = STATE(66),
    [sym_verbatim] = STATE(29),
    [sym_bold_open] = STATE(10),
    [sym_bold] = STATE(29),
    [sym_italic_open] = STATE(26),
    [sym_italic] = STATE(29),
    [sym__non_ws] = STATE(7),
    [sym__newline_non_ws] = STATE(32),
    [anon_sym_LF] = ACTIONS(56),
    [anon_sym_CR] = ACTIONS(58),
    [anon_sym_CR_LF] = ACTIONS(56),
    [sym_word] = ACTIONS(56),
    [sym_ws] = ACTIONS(56),
    [aux_sym_punc_token1] = ACTIONS(56),
    [aux_sym_punc_token2] = ACTIONS(56),
    [aux_sym_punc_token3] = ACTIONS(56),
    [anon_sym_STAR] = ACTIONS(58),
    [anon_sym_SLASH] = ACTIONS(58),
    [anon_sym_BQUOTE] = ACTIONS(58),
    [anon_sym_DOT] = ACTIONS(56),
    [anon_sym_COLON] = ACTIONS(56),
    [sym__paragraph_break] = ACTIONS(56),
    [sym__close_conflict] = ACTIONS(56),
  },
  [6] = {
    [sym_punc] = STATE(7),
    [sym_verbatim_open] = STATE(66),
    [sym_verbatim] = STATE(29),
    [sym_bold_open] = STATE(10),
    [sym_bold] = STATE(29),
    [sym_italic_open] = STATE(26),
    [sym_italic] = STATE(29),
    [sym__non_ws] = STATE(7),
    [sym__newline_non_ws] = STATE(32),
    [anon_sym_LF] = ACTIONS(60),
    [anon_sym_CR] = ACTIONS(62),
    [anon_sym_CR_LF] = ACTIONS(60),
    [sym_word] = ACTIONS(60),
    [sym_ws] = ACTIONS(60),
    [aux_sym_punc_token1] = ACTIONS(60),
    [aux_sym_punc_token2] = ACTIONS(60),
    [aux_sym_punc_token3] = ACTIONS(60),
    [anon_sym_STAR] = ACTIONS(62),
    [anon_sym_SLASH] = ACTIONS(62),
    [anon_sym_BQUOTE] = ACTIONS(62),
    [anon_sym_DOT] = ACTIONS(60),
    [anon_sym_COLON] = ACTIONS(60),
    [sym__paragraph_break] = ACTIONS(60),
    [sym__close_conflict] = ACTIONS(60),
  },
  [7] = {
    [sym_punc] = STATE(7),
    [sym_verbatim_open] = STATE(66),
    [sym_verbatim] = STATE(29),
    [sym_bold_open] = STATE(10),
    [sym_bold] = STATE(29),
    [sym_italic_open] = STATE(26),
    [sym_italic] = STATE(29),
    [sym__non_ws] = STATE(7),
    [sym__newline_non_ws] = STATE(32),
    [anon_sym_LF] = ACTIONS(64),
    [anon_sym_CR] = ACTIONS(66),
    [anon_sym_CR_LF] = ACTIONS(64),
    [sym_word] = ACTIONS(64),
    [sym_ws] = ACTIONS(64),
    [aux_sym_punc_token1] = ACTIONS(64),
    [aux_sym_punc_token2] = ACTIONS(64),
    [aux_sym_punc_token3] = ACTIONS(64),
    [anon_sym_STAR] = ACTIONS(66),
    [anon_sym_SLASH] = ACTIONS(66),
    [anon_sym_BQUOTE] = ACTIONS(66),
    [anon_sym_DOT] = ACTIONS(64),
    [anon_sym_COLON] = ACTIONS(64),
    [sym__paragraph_break] = ACTIONS(64),
    [sym__close_conflict] = ACTIONS(64),
  },
  [8] = {
    [sym_punc] = STATE(69),
    [sym_verbatim_open] = STATE(76),
    [sym_verbatim] = STATE(55),
    [sym_bold_open] = STATE(11),
    [sym__bold_non_ws] = STATE(107),
    [sym_bold] = STATE(58),
    [sym_italic_open] = STATE(27),
    [sym__italic_non_ws] = STATE(22),
    [sym_italic] = STATE(93),
    [sym_word] = ACTIONS(68),
    [aux_sym_punc_token1] = ACTIONS(70),
    [aux_sym_punc_token2] = ACTIONS(70),
    [aux_sym_punc_token3] = ACTIONS(70),
    [anon_sym_STAR] = ACTIONS(72),
    [anon_sym_SLASH] = ACTIONS(74),
    [anon_sym_BQUOTE] = ACTIONS(76),
    [anon_sym_DOT] = ACTIONS(70),
    [anon_sym_COLON] = ACTIONS(70),
    [sym__close_conflict] = ACTIONS(70),
  },
  [9] = {
    [sym_punc] = STATE(69),
    [sym_verbatim_open] = STATE(76),
    [sym_verbatim] = STATE(55),
    [sym_bold_open] = STATE(11),
    [sym__bold_non_ws] = STATE(104),
    [sym_bold] = STATE(58),
    [sym_italic_open] = STATE(27),
    [sym__italic_non_ws] = STATE(22),
    [sym_italic] = STATE(93),
    [sym_word] = ACTIONS(68),
    [aux_sym_punc_token1] = ACTIONS(70),
    [aux_sym_punc_token2] = ACTIONS(70),
    [aux_sym_punc_token3] = ACTIONS(70),
    [anon_sym_STAR] = ACTIONS(72),
    [anon_sym_SLASH] = ACTIONS(74),
    [anon_sym_BQUOTE] = ACTIONS(76),
    [anon_sym_DOT] = ACTIONS(70),
    [anon_sym_COLON] = ACTIONS(70),
    [sym__close_conflict] = ACTIONS(70),
  },
  [10] = {
    [sym_punc] = STATE(69),
    [sym_verbatim_open] = STATE(76),
    [sym_verbatim] = STATE(55),
    [sym_bold_open] = STATE(11),
    [sym__bold_non_ws] = STATE(101),
    [sym_bold] = STATE(58),
    [sym_italic_open] = STATE(27),
    [sym__italic_non_ws] = STATE(22),
    [sym_italic] = STATE(93),
    [sym_word] = ACTIONS(68),
    [aux_sym_punc_token1] = ACTIONS(70),
    [aux_sym_punc_token2] = ACTIONS(70),
    [aux_sym_punc_token3] = ACTIONS(70),
    [anon_sym_STAR] = ACTIONS(72),
    [anon_sym_SLASH] = ACTIONS(74),
    [anon_sym_BQUOTE] = ACTIONS(76),
    [anon_sym_DOT] = ACTIONS(70),
    [anon_sym_COLON] = ACTIONS(70),
    [sym__close_conflict] = ACTIONS(70),
  },
  [11] = {
    [sym_punc] = STATE(69),
    [sym_verbatim_open] = STATE(76),
    [sym_verbatim] = STATE(55),
    [sym_bold_open] = STATE(11),
    [sym__bold_non_ws] = STATE(95),
    [sym_bold] = STATE(58),
    [sym_italic_open] = STATE(27),
    [sym__italic_non_ws] = STATE(22),
    [sym_italic] = STATE(93),
    [sym_word] = ACTIONS(68),
    [aux_sym_punc_token1] = ACTIONS(70),
    [aux_sym_punc_token2] = ACTIONS(70),
    [aux_sym_punc_token3] = ACTIONS(70),
    [anon_sym_STAR] = ACTIONS(72),
    [anon_sym_SLASH] = ACTIONS(74),
    [anon_sym_BQUOTE] = ACTIONS(76),
    [anon_sym_DOT] = ACTIONS(70),
    [anon_sym_COLON] = ACTIONS(70),
    [sym__close_conflict] = ACTIONS(70),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    STATE(8), 1,
      sym_bold_open,
    STATE(76), 1,
      sym_verbatim_open,
    STATE(12), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(52), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(80), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(78), 9,
      sym__close_conflict,
      sym_bold_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [31] = 10,
    ACTIONS(9), 1,
      sym_word,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      anon_sym_SLASH,
    ACTIONS(17), 1,
      anon_sym_BQUOTE,
    STATE(10), 1,
      sym_bold_open,
    STATE(26), 1,
      sym_italic_open,
    STATE(66), 1,
      sym_verbatim_open,
    STATE(6), 2,
      sym_punc,
      sym__non_ws,
    STATE(29), 3,
      sym_verbatim,
      sym_bold,
      sym_italic,
    ACTIONS(11), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [70] = 6,
    STATE(9), 1,
      sym_bold_open,
    STATE(80), 1,
      sym_verbatim_open,
    STATE(14), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(51), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(80), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(78), 9,
      sym__close_conflict,
      sym_italic_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [101] = 10,
    ACTIONS(9), 1,
      sym_word,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      anon_sym_SLASH,
    ACTIONS(17), 1,
      anon_sym_BQUOTE,
    STATE(10), 1,
      sym_bold_open,
    STATE(26), 1,
      sym_italic_open,
    STATE(66), 1,
      sym_verbatim_open,
    STATE(5), 2,
      sym_punc,
      sym__non_ws,
    STATE(29), 3,
      sym_verbatim,
      sym_bold,
      sym_italic,
    ACTIONS(11), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [140] = 11,
    ACTIONS(82), 1,
      sym_word,
    ACTIONS(84), 1,
      sym_ws,
    ACTIONS(88), 1,
      anon_sym_STAR,
    ACTIONS(90), 1,
      anon_sym_SLASH,
    ACTIONS(92), 1,
      anon_sym_BQUOTE,
    ACTIONS(94), 1,
      sym_italic_close,
    STATE(9), 1,
      sym_bold_open,
    STATE(80), 1,
      sym_verbatim_open,
    STATE(14), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(51), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(86), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [181] = 7,
    ACTIONS(100), 1,
      sym_bold_close,
    STATE(8), 1,
      sym_bold_open,
    STATE(76), 1,
      sym_verbatim_open,
    STATE(12), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(52), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(98), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(96), 8,
      sym__close_conflict,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [214] = 6,
    STATE(9), 1,
      sym_bold_open,
    STATE(80), 1,
      sym_verbatim_open,
    STATE(14), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(51), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(98), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(96), 9,
      sym__close_conflict,
      sym_italic_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [245] = 11,
    ACTIONS(82), 1,
      sym_word,
    ACTIONS(84), 1,
      sym_ws,
    ACTIONS(88), 1,
      anon_sym_STAR,
    ACTIONS(90), 1,
      anon_sym_SLASH,
    ACTIONS(92), 1,
      anon_sym_BQUOTE,
    ACTIONS(102), 1,
      sym_italic_close,
    STATE(9), 1,
      sym_bold_open,
    STATE(80), 1,
      sym_verbatim_open,
    STATE(14), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(51), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(86), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [286] = 7,
    ACTIONS(104), 1,
      sym_bold_close,
    STATE(8), 1,
      sym_bold_open,
    STATE(76), 1,
      sym_verbatim_open,
    STATE(12), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(52), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(80), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(78), 8,
      sym__close_conflict,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [319] = 6,
    STATE(8), 1,
      sym_bold_open,
    STATE(76), 1,
      sym_verbatim_open,
    STATE(12), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(52), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(98), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(96), 9,
      sym__close_conflict,
      sym_bold_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [350] = 10,
    ACTIONS(72), 1,
      anon_sym_STAR,
    ACTIONS(76), 1,
      anon_sym_BQUOTE,
    ACTIONS(106), 1,
      sym_word,
    ACTIONS(108), 1,
      sym_ws,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    STATE(8), 1,
      sym_bold_open,
    STATE(76), 1,
      sym_verbatim_open,
    STATE(20), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(52), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(70), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [388] = 5,
    ACTIONS(116), 1,
      anon_sym_COLON,
    ACTIONS(118), 1,
      sym__open_conflict,
    STATE(88), 1,
      sym_link_modifier,
    ACTIONS(114), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(112), 10,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [416] = 4,
    ACTIONS(116), 1,
      anon_sym_COLON,
    STATE(98), 1,
      sym_link_modifier,
    ACTIONS(58), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(56), 10,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [441] = 9,
    ACTIONS(72), 1,
      anon_sym_STAR,
    ACTIONS(76), 1,
      anon_sym_BQUOTE,
    ACTIONS(106), 1,
      sym_word,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    STATE(8), 1,
      sym_bold_open,
    STATE(76), 1,
      sym_verbatim_open,
    STATE(17), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(52), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(70), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [476] = 9,
    ACTIONS(82), 1,
      sym_word,
    ACTIONS(88), 1,
      anon_sym_STAR,
    ACTIONS(90), 1,
      anon_sym_SLASH,
    ACTIONS(92), 1,
      anon_sym_BQUOTE,
    STATE(9), 1,
      sym_bold_open,
    STATE(80), 1,
      sym_verbatim_open,
    STATE(16), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(51), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(86), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [511] = 9,
    ACTIONS(82), 1,
      sym_word,
    ACTIONS(88), 1,
      anon_sym_STAR,
    ACTIONS(90), 1,
      anon_sym_SLASH,
    ACTIONS(92), 1,
      anon_sym_BQUOTE,
    STATE(9), 1,
      sym_bold_open,
    STATE(80), 1,
      sym_verbatim_open,
    STATE(19), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(51), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(86), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [546] = 9,
    ACTIONS(82), 1,
      sym_word,
    ACTIONS(88), 1,
      anon_sym_STAR,
    ACTIONS(90), 1,
      anon_sym_SLASH,
    ACTIONS(92), 1,
      anon_sym_BQUOTE,
    STATE(9), 1,
      sym_bold_open,
    STATE(80), 1,
      sym_verbatim_open,
    STATE(18), 2,
      sym_punc,
      sym__italic_non_ws,
    STATE(51), 2,
      sym_verbatim,
      sym_bold,
    ACTIONS(86), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [581] = 4,
    ACTIONS(116), 1,
      anon_sym_COLON,
    STATE(109), 1,
      sym_link_modifier,
    ACTIONS(114), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(112), 10,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [606] = 4,
    ACTIONS(122), 1,
      anon_sym_CR,
    ACTIONS(127), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(120), 4,
      sym__paragraph_break,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_ws,
    ACTIONS(124), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [630] = 2,
    ACTIONS(122), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(120), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [650] = 2,
    ACTIONS(66), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(64), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [670] = 4,
    ACTIONS(122), 1,
      anon_sym_CR,
    ACTIONS(133), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(120), 4,
      sym__paragraph_break,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_ws,
    ACTIONS(130), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [694] = 2,
    ACTIONS(138), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(136), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [714] = 2,
    ACTIONS(142), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(140), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [734] = 2,
    ACTIONS(146), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(144), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [754] = 2,
    ACTIONS(66), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(64), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [774] = 2,
    ACTIONS(58), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(56), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [794] = 2,
    ACTIONS(150), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(148), 11,
      sym__close_conflict,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [814] = 4,
    ACTIONS(122), 1,
      anon_sym_CR,
    ACTIONS(155), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(120), 4,
      sym__paragraph_break,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_ws,
    ACTIONS(152), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [838] = 2,
    ACTIONS(160), 4,
      anon_sym_CR,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(158), 11,
      sym__paragraph_break,
      sym__close_conflict,
      anon_sym_LF,
      anon_sym_CR_LF,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [858] = 6,
    ACTIONS(162), 1,
      sym_word,
    ACTIONS(164), 1,
      sym_ws,
    ACTIONS(170), 1,
      sym_verbatim_close,
    STATE(44), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(168), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(166), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [885] = 3,
    STATE(44), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(174), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(172), 9,
      sym__close_conflict,
      sym_verbatim_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [906] = 3,
    STATE(44), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(178), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(176), 9,
      sym__close_conflict,
      sym_verbatim_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [927] = 6,
    ACTIONS(162), 1,
      sym_word,
    ACTIONS(164), 1,
      sym_ws,
    ACTIONS(180), 1,
      sym_verbatim_close,
    STATE(44), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(168), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(166), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [954] = 6,
    ACTIONS(162), 1,
      sym_word,
    ACTIONS(164), 1,
      sym_ws,
    ACTIONS(182), 1,
      sym_verbatim_close,
    STATE(44), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(168), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(166), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [981] = 5,
    ACTIONS(100), 1,
      sym_bold_close,
    ACTIONS(116), 1,
      anon_sym_COLON,
    STATE(110), 1,
      sym_link_modifier,
    ACTIONS(98), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(96), 7,
      sym__close_conflict,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [1005] = 4,
    ACTIONS(116), 1,
      anon_sym_COLON,
    STATE(106), 1,
      sym_link_modifier,
    ACTIONS(98), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(96), 8,
      sym__close_conflict,
      sym_bold_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [1027] = 4,
    ACTIONS(116), 1,
      anon_sym_COLON,
    STATE(102), 1,
      sym_link_modifier,
    ACTIONS(98), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(96), 8,
      sym__close_conflict,
      sym_italic_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [1049] = 4,
    ACTIONS(116), 1,
      anon_sym_COLON,
    STATE(89), 1,
      sym_link_modifier,
    ACTIONS(186), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(184), 8,
      sym__close_conflict,
      sym_bold_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [1071] = 4,
    ACTIONS(116), 1,
      anon_sym_COLON,
    STATE(100), 1,
      sym_link_modifier,
    ACTIONS(186), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(184), 8,
      sym__close_conflict,
      sym_italic_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [1093] = 4,
    ACTIONS(116), 1,
      anon_sym_COLON,
    STATE(105), 1,
      sym_link_modifier,
    ACTIONS(186), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(184), 8,
      sym__close_conflict,
      sym_bold_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [1115] = 5,
    ACTIONS(116), 1,
      anon_sym_COLON,
    ACTIONS(188), 1,
      sym_bold_close,
    STATE(87), 1,
      sym_link_modifier,
    ACTIONS(186), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(184), 7,
      sym__close_conflict,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [1139] = 4,
    ACTIONS(116), 1,
      anon_sym_COLON,
    STATE(90), 1,
      sym_link_modifier,
    ACTIONS(186), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(184), 8,
      sym__close_conflict,
      sym_italic_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [1161] = 5,
    ACTIONS(116), 1,
      anon_sym_COLON,
    ACTIONS(188), 1,
      sym_bold_close,
    STATE(108), 1,
      sym_link_modifier,
    ACTIONS(186), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(184), 7,
      sym__close_conflict,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [1185] = 2,
    ACTIONS(160), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(158), 9,
      sym__close_conflict,
      sym_bold_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1202] = 3,
    ACTIONS(194), 1,
      sym_bold_close,
    ACTIONS(192), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(190), 8,
      sym__close_conflict,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1221] = 4,
    ACTIONS(116), 1,
      anon_sym_COLON,
    STATE(103), 1,
      sym_link_modifier,
    ACTIONS(186), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(184), 7,
      sym__close_conflict,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [1242] = 2,
    ACTIONS(122), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(120), 9,
      sym__close_conflict,
      sym_italic_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1259] = 4,
    ACTIONS(116), 1,
      anon_sym_COLON,
    STATE(111), 1,
      sym_link_modifier,
    ACTIONS(98), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(96), 7,
      sym__close_conflict,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
  [1280] = 2,
    ACTIONS(192), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(190), 9,
      sym__close_conflict,
      sym_bold_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1297] = 3,
    ACTIONS(100), 1,
      sym_bold_close,
    ACTIONS(98), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(96), 8,
      sym__close_conflict,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1316] = 2,
    ACTIONS(98), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(96), 9,
      sym__close_conflict,
      sym_bold_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1333] = 2,
    ACTIONS(160), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(158), 9,
      sym__close_conflict,
      sym_italic_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1350] = 2,
    ACTIONS(146), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(144), 9,
      sym__close_conflict,
      sym_italic_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1367] = 4,
    ACTIONS(196), 1,
      sym_word,
    STATE(45), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(168), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(166), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1388] = 3,
    ACTIONS(120), 2,
      sym_italic_close,
      sym_ws,
    ACTIONS(133), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(130), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1407] = 3,
    ACTIONS(120), 2,
      sym_italic_close,
      sym_ws,
    ACTIONS(155), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(152), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1426] = 3,
    ACTIONS(188), 1,
      sym_bold_close,
    ACTIONS(186), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(184), 8,
      sym__close_conflict,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1445] = 2,
    ACTIONS(122), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(120), 9,
      sym__close_conflict,
      sym_bold_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1462] = 2,
    ACTIONS(192), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(190), 9,
      sym__close_conflict,
      sym_italic_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1479] = 2,
    ACTIONS(122), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(120), 9,
      sym__close_conflict,
      sym_verbatim_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1496] = 3,
    ACTIONS(120), 2,
      sym_bold_close,
      sym_ws,
    ACTIONS(155), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(152), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1515] = 3,
    ACTIONS(120), 2,
      sym_bold_close,
      sym_ws,
    ACTIONS(127), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(124), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1534] = 3,
    ACTIONS(120), 2,
      sym_bold_close,
      sym_ws,
    ACTIONS(133), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(130), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1553] = 4,
    ACTIONS(198), 1,
      sym_word,
    STATE(42), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(168), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(166), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1574] = 4,
    ACTIONS(200), 1,
      sym_word,
    STATE(43), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(168), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(166), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1595] = 2,
    ACTIONS(146), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(144), 9,
      sym__close_conflict,
      sym_bold_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1612] = 2,
    ACTIONS(98), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(96), 9,
      sym__close_conflict,
      sym_italic_close,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1629] = 4,
    ACTIONS(202), 1,
      sym_word,
    STATE(46), 2,
      sym_punc,
      sym__verbatim_non_ws,
    ACTIONS(168), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(166), 6,
      sym__close_conflict,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1650] = 2,
    ACTIONS(160), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(158), 8,
      sym__close_conflict,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1666] = 2,
    ACTIONS(192), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(190), 8,
      sym__close_conflict,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1682] = 2,
    ACTIONS(98), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(96), 8,
      sym__close_conflict,
      sym_word,
      sym_ws,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1698] = 2,
    ACTIONS(206), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(204), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1713] = 2,
    ACTIONS(210), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(208), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1728] = 2,
    ACTIONS(214), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
    ACTIONS(212), 7,
      sym__close_conflict,
      sym_word,
      aux_sym_punc_token1,
      aux_sym_punc_token2,
      aux_sym_punc_token3,
      anon_sym_DOT,
      anon_sym_COLON,
  [1743] = 9,
    ACTIONS(216), 1,
      anon_sym_STAR,
    ACTIONS(218), 1,
      anon_sym_SLASH,
    ACTIONS(220), 1,
      anon_sym_BQUOTE,
    STATE(11), 1,
      sym_bold_open,
    STATE(27), 1,
      sym_italic_open,
    STATE(47), 1,
      sym_verbatim,
    STATE(60), 1,
      sym_bold,
    STATE(76), 1,
      sym_verbatim_open,
    STATE(92), 1,
      sym_italic,
  [1771] = 7,
    ACTIONS(216), 1,
      anon_sym_STAR,
    ACTIONS(218), 1,
      anon_sym_SLASH,
    ACTIONS(220), 1,
      anon_sym_BQUOTE,
    STATE(10), 1,
      sym_bold_open,
    STATE(26), 1,
      sym_italic_open,
    STATE(66), 1,
      sym_verbatim_open,
    STATE(24), 3,
      sym_verbatim,
      sym_bold,
      sym_italic,
  [1795] = 5,
    ACTIONS(216), 1,
      anon_sym_STAR,
    ACTIONS(220), 1,
      anon_sym_BQUOTE,
    STATE(8), 1,
      sym_bold_open,
    STATE(76), 1,
      sym_verbatim_open,
    STATE(48), 2,
      sym_verbatim,
      sym_bold,
  [1812] = 5,
    ACTIONS(216), 1,
      anon_sym_STAR,
    ACTIONS(220), 1,
      anon_sym_BQUOTE,
    STATE(9), 1,
      sym_bold_open,
    STATE(80), 1,
      sym_verbatim_open,
    STATE(49), 2,
      sym_verbatim,
      sym_bold,
  [1829] = 1,
    ACTIONS(222), 4,
      sym_word,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_BQUOTE,
  [1836] = 3,
    ACTIONS(100), 1,
      sym_bold_close,
    ACTIONS(116), 1,
      anon_sym_COLON,
    STATE(112), 1,
      sym_link_modifier,
  [1846] = 3,
    ACTIONS(116), 1,
      anon_sym_COLON,
    ACTIONS(188), 1,
      sym_bold_close,
    STATE(99), 1,
      sym_link_modifier,
  [1856] = 1,
    ACTIONS(136), 2,
      sym_bold_close,
      anon_sym_COLON,
  [1861] = 1,
    ACTIONS(224), 1,
      sym_bold_close,
  [1865] = 1,
    ACTIONS(100), 1,
      sym_bold_close,
  [1869] = 1,
    ACTIONS(226), 1,
      ts_builtin_sym_end,
  [1873] = 1,
    ACTIONS(228), 1,
      sym_word,
  [1877] = 1,
    ACTIONS(230), 1,
      sym_word,
  [1881] = 1,
    ACTIONS(232), 1,
      sym_word,
  [1885] = 1,
    ACTIONS(234), 1,
      sym_bold_close,
  [1889] = 1,
    ACTIONS(236), 1,
      sym_word,
  [1893] = 1,
    ACTIONS(238), 1,
      sym_word,
  [1897] = 1,
    ACTIONS(240), 1,
      sym_bold_close,
  [1901] = 1,
    ACTIONS(242), 1,
      sym_word,
  [1905] = 1,
    ACTIONS(244), 1,
      sym_word,
  [1909] = 1,
    ACTIONS(246), 1,
      sym_bold_close,
  [1913] = 1,
    ACTIONS(248), 1,
      sym_word,
  [1917] = 1,
    ACTIONS(250), 1,
      sym_word,
  [1921] = 1,
    ACTIONS(252), 1,
      sym_word,
  [1925] = 1,
    ACTIONS(254), 1,
      sym_word,
  [1929] = 1,
    ACTIONS(256), 1,
      sym_word,
  [1933] = 1,
    ACTIONS(194), 1,
      sym_bold_close,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(12)] = 0,
  [SMALL_STATE(13)] = 31,
  [SMALL_STATE(14)] = 70,
  [SMALL_STATE(15)] = 101,
  [SMALL_STATE(16)] = 140,
  [SMALL_STATE(17)] = 181,
  [SMALL_STATE(18)] = 214,
  [SMALL_STATE(19)] = 245,
  [SMALL_STATE(20)] = 286,
  [SMALL_STATE(21)] = 319,
  [SMALL_STATE(22)] = 350,
  [SMALL_STATE(23)] = 388,
  [SMALL_STATE(24)] = 416,
  [SMALL_STATE(25)] = 441,
  [SMALL_STATE(26)] = 476,
  [SMALL_STATE(27)] = 511,
  [SMALL_STATE(28)] = 546,
  [SMALL_STATE(29)] = 581,
  [SMALL_STATE(30)] = 606,
  [SMALL_STATE(31)] = 630,
  [SMALL_STATE(32)] = 650,
  [SMALL_STATE(33)] = 670,
  [SMALL_STATE(34)] = 694,
  [SMALL_STATE(35)] = 714,
  [SMALL_STATE(36)] = 734,
  [SMALL_STATE(37)] = 754,
  [SMALL_STATE(38)] = 774,
  [SMALL_STATE(39)] = 794,
  [SMALL_STATE(40)] = 814,
  [SMALL_STATE(41)] = 838,
  [SMALL_STATE(42)] = 858,
  [SMALL_STATE(43)] = 885,
  [SMALL_STATE(44)] = 906,
  [SMALL_STATE(45)] = 927,
  [SMALL_STATE(46)] = 954,
  [SMALL_STATE(47)] = 981,
  [SMALL_STATE(48)] = 1005,
  [SMALL_STATE(49)] = 1027,
  [SMALL_STATE(50)] = 1049,
  [SMALL_STATE(51)] = 1071,
  [SMALL_STATE(52)] = 1093,
  [SMALL_STATE(53)] = 1115,
  [SMALL_STATE(54)] = 1139,
  [SMALL_STATE(55)] = 1161,
  [SMALL_STATE(56)] = 1185,
  [SMALL_STATE(57)] = 1202,
  [SMALL_STATE(58)] = 1221,
  [SMALL_STATE(59)] = 1242,
  [SMALL_STATE(60)] = 1259,
  [SMALL_STATE(61)] = 1280,
  [SMALL_STATE(62)] = 1297,
  [SMALL_STATE(63)] = 1316,
  [SMALL_STATE(64)] = 1333,
  [SMALL_STATE(65)] = 1350,
  [SMALL_STATE(66)] = 1367,
  [SMALL_STATE(67)] = 1388,
  [SMALL_STATE(68)] = 1407,
  [SMALL_STATE(69)] = 1426,
  [SMALL_STATE(70)] = 1445,
  [SMALL_STATE(71)] = 1462,
  [SMALL_STATE(72)] = 1479,
  [SMALL_STATE(73)] = 1496,
  [SMALL_STATE(74)] = 1515,
  [SMALL_STATE(75)] = 1534,
  [SMALL_STATE(76)] = 1553,
  [SMALL_STATE(77)] = 1574,
  [SMALL_STATE(78)] = 1595,
  [SMALL_STATE(79)] = 1612,
  [SMALL_STATE(80)] = 1629,
  [SMALL_STATE(81)] = 1650,
  [SMALL_STATE(82)] = 1666,
  [SMALL_STATE(83)] = 1682,
  [SMALL_STATE(84)] = 1698,
  [SMALL_STATE(85)] = 1713,
  [SMALL_STATE(86)] = 1728,
  [SMALL_STATE(87)] = 1743,
  [SMALL_STATE(88)] = 1771,
  [SMALL_STATE(89)] = 1795,
  [SMALL_STATE(90)] = 1812,
  [SMALL_STATE(91)] = 1829,
  [SMALL_STATE(92)] = 1836,
  [SMALL_STATE(93)] = 1846,
  [SMALL_STATE(94)] = 1856,
  [SMALL_STATE(95)] = 1861,
  [SMALL_STATE(96)] = 1865,
  [SMALL_STATE(97)] = 1869,
  [SMALL_STATE(98)] = 1873,
  [SMALL_STATE(99)] = 1877,
  [SMALL_STATE(100)] = 1881,
  [SMALL_STATE(101)] = 1885,
  [SMALL_STATE(102)] = 1889,
  [SMALL_STATE(103)] = 1893,
  [SMALL_STATE(104)] = 1897,
  [SMALL_STATE(105)] = 1901,
  [SMALL_STATE(106)] = 1905,
  [SMALL_STATE(107)] = 1909,
  [SMALL_STATE(108)] = 1913,
  [SMALL_STATE(109)] = 1917,
  [SMALL_STATE(110)] = 1921,
  [SMALL_STATE(111)] = 1925,
  [SMALL_STATE(112)] = 1929,
  [SMALL_STATE(113)] = 1933,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(2),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(2),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(23),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(31),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(40),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(30),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(33),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__non_ws, 3),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__non_ws, 3),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__newline_non_ws, 2),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__newline_non_ws, 2),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__non_ws, 2),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__non_ws, 2),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__italic_non_ws, 2),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__italic_non_ws, 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__italic_non_ws, 3),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__italic_non_ws, 3),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bold_non_ws, 3),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bold_non_ws, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__non_ws, 1),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__non_ws, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_punc, 1),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_punc, 1),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_punc, 1), REDUCE(sym_italic_open, 1),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_punc, 1), REDUCE(sym_italic_open, 1),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_punc, 1), REDUCE(sym_verbatim_open, 1),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_punc, 1), REDUCE(sym_verbatim_open, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3, .dynamic_precedence = 1),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 3, .dynamic_precedence = 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__non_ws, 5),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__non_ws, 5),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim, 3, .dynamic_precedence = 2),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim, 3, .dynamic_precedence = 2),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_punc, 1), REDUCE(sym_bold_open, 1),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_punc, 1), REDUCE(sym_bold_open, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3, .dynamic_precedence = 1),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold, 3, .dynamic_precedence = 1),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__verbatim_non_ws, 3),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__verbatim_non_ws, 3),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__verbatim_non_ws, 2),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__verbatim_non_ws, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__italic_non_ws, 1),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__italic_non_ws, 1),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bold_non_ws, 1),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__italic_non_ws, 5),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__italic_non_ws, 5),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bold_non_ws, 5),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_open, 1),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_open, 1),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold_open, 1),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold_open, 1),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic_open, 1),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic_open, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_modifier, 1, .dynamic_precedence = 1),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [226] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__paragraph_break = 0,
  ts_external_token__open_conflict = 1,
  ts_external_token__close_conflict = 2,
  ts_external_token_bold_close = 3,
  ts_external_token_italic_close = 4,
  ts_external_token_verbatim_close = 5,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__paragraph_break] = sym__paragraph_break,
  [ts_external_token__open_conflict] = sym__open_conflict,
  [ts_external_token__close_conflict] = sym__close_conflict,
  [ts_external_token_bold_close] = sym_bold_close,
  [ts_external_token_italic_close] = sym_italic_close,
  [ts_external_token_verbatim_close] = sym_verbatim_close,
};

static const bool ts_external_scanner_states[9][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__paragraph_break] = true,
    [ts_external_token__open_conflict] = true,
    [ts_external_token__close_conflict] = true,
    [ts_external_token_bold_close] = true,
    [ts_external_token_italic_close] = true,
    [ts_external_token_verbatim_close] = true,
  },
  [2] = {
    [ts_external_token__close_conflict] = true,
  },
  [3] = {
    [ts_external_token__paragraph_break] = true,
    [ts_external_token__close_conflict] = true,
  },
  [4] = {
    [ts_external_token__close_conflict] = true,
    [ts_external_token_bold_close] = true,
  },
  [5] = {
    [ts_external_token__close_conflict] = true,
    [ts_external_token_italic_close] = true,
  },
  [6] = {
    [ts_external_token__paragraph_break] = true,
    [ts_external_token__open_conflict] = true,
    [ts_external_token__close_conflict] = true,
  },
  [7] = {
    [ts_external_token__close_conflict] = true,
    [ts_external_token_verbatim_close] = true,
  },
  [8] = {
    [ts_external_token_bold_close] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_norgtest_external_scanner_create(void);
void tree_sitter_norgtest_external_scanner_destroy(void *);
bool tree_sitter_norgtest_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_norgtest_external_scanner_serialize(void *, char *);
void tree_sitter_norgtest_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_norgtest(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_norgtest_external_scanner_create,
      tree_sitter_norgtest_external_scanner_destroy,
      tree_sitter_norgtest_external_scanner_scan,
      tree_sitter_norgtest_external_scanner_serialize,
      tree_sitter_norgtest_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
